### ISSUE TITLE
Improve documentation on Slack integration setup?

### ISSUE THREAD

**Issue by nickchappell** [splunk-terraform/terraform-provider-signalfx#103]
I set up a new Slack integration via the SFX/Slack web UIs recently. I wanted to port it over to TF code, however, the Slack UI doesn't show any webhook URL for the SFX integration, and an existing SFX integration doesn't show what webhook URL, if any, it's using via the SFX web UI.

Could the Slack integration resource's documentation be updated on what/how the integration needs to be set up on the Slack side so a web hook URL is available?

**Comment by cory-signalfx** [comment]
Thanks @nickchappell! We'll take a look at this internally and see what we can do.

**Comment by atoulme** [comment]
This issue is closed for inactivity. Please comment or reopen if more work is needed.
