### ISSUE TITLE
Improve documentation on Slack notifications

### ISSUE THREAD

**Issue by SansGuidon** [splunk-terraform/terraform-provider-signalfx#104]
Examples from https://www.terraform.io/docs/providers/signalfx/r/detector.html shows channel name starting with `#` while `terraform plan` / `terraform apply` prohibit it. 

```
terraform apply -var-file=config.tfvars
Error: Please exclude the # from channel names in "#notifications-test"
  on main.tf line 1, in resource "signalfx_detector" "monitoring-notifications":
   1: resource "signalfx_detector" "monitoring-notifications" {
```

The related code in our `main.tf` : 
`    notifications = ["Email,custom.mail@customdomain.com", "Slack,credentialId,#notifications-test"]`

It works perfectly after removing the `#`

Note that on SignalFX UI, when configuring notifications, the `#` is added to the notifications config and `terraform plan` would show a difference. 

**Versions :**
```
Terraform v0.12.12
+ provider.signalfx v4.9.1
```

*EDIT* it looks like the problem is rather that the documentation on terraform.io is not aligned with the documentation changes performed in https://github.com/terraform-providers/terraform-provider-signalfx/commit/e3578f9a4ccfdde057fb1104930c1c83eee1a63a

**Comment by cory-signalfx** [comment]
Hey @MorganGeek,

You're absolutely right, this needs a fix. Will do today!

**Comment by cory-signalfx** [comment]
I've merged this and asked for a push to the terraform.io site. Thanks again for the heads up @MorganGeek!

**Comment by SansGuidon** [comment]
Thank you @cory-signalfx
