### ISSUE TITLE
Add support for Jira notifications

### ISSUE THREAD

**Issue by SansGuidon** [splunk-terraform/terraform-provider-signalfx#105]
This is the error returned by `terraform plan` after configuring a Jira notification via the UI. 

`Error: Unknown notification type Jira`

**Versions :**
```
Terraform v0.12.12
+ provider.signalfx v4.9.1
```

**Comment by SansGuidon** [comment]
@cory-signalfx is there any intent to work on this soon or should I better start working on this as I need it ?

**Comment by cory-signalfx** [comment]
Sorry, I missed this during travel last week. I'll get this out today!

**Comment by SansGuidon** [comment]
@cory-signalfx thank you a lot :)

**Comment by cory-signalfx** [comment]
Oops, got this in #106!
