### ISSUE TITLE
Allow dashboard permission management

### ISSUE THREAD

**Issue by cory-signalfx** [splunk-terraform/terraform-provider-signalfx#107]
The dashboard resource does not allow modifying the `authorizedWriters`!

**Comment by geoffhigginbottom** [comment]
It is currently not possible to modify the permissions of Dashboards or Dashboard Groups.  If a Terraform deployed Dashboard has its permissions modified by a user, it effectively breaks the Terraform Integration.  We need to be able to set the permissions when creating new Dashboards, but also update the configuration of existing dashboards if a user has changed them post deployment.  This will enable true Monitoring as Code using Terraform.
