### ISSUE TITLE
Subscription Validated by Service Schema 

### ISSUE THREAD

**Issue by funnybirdman** [splunk-terraform/terraform-provider-signalfx#112]
https://github.com/terraform-providers/terraform-provider-signalfx/blob/master/signalfx/resource_signalfx_azure_integration.go#L66

The service schema is being used to validate subscription. The examples show passing services names in, instead of subscription ids. 

Error 
```
* signalfx_azure_integration.test: [REDACTED SUBSCRIPTION ID] not allowed; consult the documentation for a list of valid Azure service names
```

**Comment by cory-signalfx** [comment]
Thanks @funnybirdman, on it!
