### ISSUE TITLE
Mirroring dashboards within HCL cause dashboards to be deleted

### ISSUE THREAD

**Issue by MovieStoreGuy** [splunk-terraform/terraform-provider-signalfx#121]
Using provider version: 4.9.1

The issue is when I have a dashboards configured as part of my HCL, then once you have added a link to a mirrored dashboard, the original configured dashboards are removed from SignalFx.

Note: Currently working as a proxy portraying this issue.

**Comment by cory-signalfx** [comment]
Hello @MovieStoreGuy!

I've set up a local version of this to try and replicate and need a bit more information. Here's my test case:

```
resource "signalfx_dashboard_group" "mydashboardgroup0" {
    name = "My team dashboard group"
    description = "Cool dashboard group"
}

resource "signalfx_time_chart" "mychart0" {
    name = "CPU Total Idle"

    program_text = <<-EOF
        myfilters = filter("shc_name", "prod") and filter("role", "splunk_searchhead")
        data("cpu.total.idle", filter=myfilters).publish(label="CPU Idle")
        EOF

    time_range = 3600

    plot_type = "LineChart"
    show_data_markers = true

    viz_options {
        label = "CPU Idle"
        axis = "left"
        color = "orange"
    }

    axis_left {
        label = "CPU Total Idle"
        low_watermark = 1000
    }
}

resource "signalfx_dashboard" "mydashboard0" {
    name = "My Dashboard"
    dashboard_group = signalfx_dashboard_group.mydashboardgroup0.id

    time_range = "-30m"

    filter {
        property = "collector"
        values = ["cpu", "Diamond"]
    }
    variable {
        property = "region"
        alias = "region"
        values = ["uswest-1-"]
    }
    chart {
        chart_id = signalfx_time_chart.mychart0.id
        width = 12
        height = 1
    }
}

resource "signalfx_dashboard_group" "mydashboardgroup2" {
    name = "My team dashboard group 2"
    description = "Cool dashboard group 2"

		dashboard {
			dashboard_id = signalfx_dashboard.mydashboard0.id
			name_override = "FART"
			description_override = "FARTER"
		}
}
```

This makes a group A with a dashboard B, then a group C that mirrors dashboard B.

On my end this creates correctly and subsequent `terraform plan`s are stable. I'm using Terraform 0.12.17 and provider version 4.10.2. Let me know if I need to test an older terraform or something or if my HCL is different having misunderstood the issue.

Note: It may be Monday before I can offer a full fix if we track down a problem. I'm going to be out part of today.

**Comment by MovieStoreGuy** [comment]
Hey @cory-signalfx ,

I can't get the user that had reported this to me to be able to reproduce.

I am going to close this off and reopen it once I have something concrete.

**Comment by cory-signalfx** [comment]
Sure thing, @MovieStoreGuy. Shoot me a note if you see it again!
