### ISSUE TITLE
It would be nice if we have terraform for datalinks

### ISSUE THREAD

**Issue by saikrishna547** [splunk-terraform/terraform-provider-signalfx#126]
We have automated the dashboards in our organization but the most important missing part is automating the creation of datalinks. It would be nice if we have that feature in terraform

**Comment by cory-signalfx** [comment]
You're in luck @saikrishna547, please see #125 where this is in progress. I expect to merge it in the next few days.

**Comment by saikrishna547** [comment]
Sounds great!

**Comment by cory-signalfx** [comment]
Merged, should be released later today. Thanks for the ask!

**Comment by saikrishna547** [comment]
so the documentation for that will be available at that time or is that released? Because I don't see it

**Comment by cory-signalfx** [comment]
Yes, the documentation is updated when the folks at HashiCorp make an official build. Seems nobody picked up my ask for a build yesterday so I've reasked just now. Expecting it will be available in a few hours.

**Comment by saikrishna547** [comment]
`resource "signalfx_data_link" "mydatalink_overview" {
        dashboard_id = "${signalfx_dashboard.overview.id}"
    property_name = "AWSUniqueId"
    
target_signalfx_dashboard {
      is_default = true
      name = "Overview AWS_UniqueID data link to host dashboard"
            dashboard_group_id = "${signalfx_dashboard_group.mdcat_dashboard_group.id}"
            dashboard_id = "${signalfx_dashboard.host.id}"
    }
}`
When I try to create a datalink It says `argument dashboard_id is not expected here'
I am able to create once I remove the dashboard_id present on the top(but it makes it global). But I want to create a dashboard-specific link but wasn't able to do so. Can you please check this? or let me know if I missed anything from the below docs.
https://www.terraform.io/docs/providers/signalfx/r/data_link.html

**Comment by cory-signalfx** [comment]
I just sent [a commit to fix this](https://github.com/terraform-providers/terraform-provider-signalfx/commit/f704bcb7761e1ad3d5d6478986a40032bae25c7c)!

**Comment by cory-signalfx** [comment]
So, in short you'd want to use `context_dashboard_id`. :)

**Comment by saikrishna547** [comment]
resource "signalfx_data_link" "mydatalink_overview_1" {
  context_dashboard_id = "signalfx_dashboard.overview.id"
  property_name = "AWSUniqueId"
  target_signalfx_dashboard {
    is_default = true
    name = "Overview AWS_UniqueID data link to host dashboard"
    dashboard_group_id = "signalfx_dashboard_group.mdcat_dashboard_group.id"
    dashboard_id = "signalfx_dashboard.host.id"
  }
}


Error while creating the datalinks says 
"Error: Bad status 400: {
  "code" : 400,
  "message" : "Failed to deserialize payload at: sf.domain.crosslink.CrossLink[\"contextId\"]"
}

  on datalinks.tf line 2, in resource "signalfx_data_link" "mydatalink_overview_1":
   2: resource "signalfx_data_link" "mydatalink_overview_1" {

**Comment by saikrishna547** [comment]
Hello @cory-signalfx , My dashboard has complete unique properties but it's throwing me an error like this. All the datalinks within that dashboard is unique.

Error: Bad status 400: {
  "code" : 400,
  "message" : "Cannot create multiple cross links for the same property value combination"
}

  on datalinks.tf line 159, in resource "signalfx_data_link" "mydatalink_ec2_instances_2":
 159: resource "signalfx_data_link" "mydatalink_ec2_instances_2" {
