### ISSUE TITLE
Can't use credentialId in Webhook notifications for Detector rules

### ISSUE THREAD

**Issue by shwin** [splunk-terraform/terraform-provider-signalfx#128]
I'd like to use a webhook notification in a signalFX detector, but only provide the `credentialId`.

The official API doc  (https://developers.signalfx.com/detectors_reference.html#operation/Create%20Single%20Detector, expand rules and notifications and click on webhook) says this is possible:
![image](https://user-images.githubusercontent.com/1700973/70954374-cb987f80-2021-11ea-8b91-46090aaa7371.png)

So in Terraform, I have a detector with a rule like:
```
rule {
    detect_label = "critical"
    severity     = "Critical"

    notifications = [
      "Webhook,SOMEID",
    ]
  }
```

That gives me an error:
`Error: Invalid Webhook notification string, please consult the documentation (not enough parts)`

Ok, fine, I don't mind providing the URL:
```
  notifications = [
      "Webhook,SOMEID,,http://mywebsite.com",
    ]
```
But I get: `"message" : "Either url or credentialId must be defined, both were defined."`

If I do it like
```
  notifications = [
      "Webhook,SOMEID,,",
    ]
```

I get `Error: Invalid Webhook URL ""`

So, is there any way I can use `credentialId` in terraform?

**Comment by shwin** [comment]
I figure this is just a bug in this logic: https://github.com/terraform-providers/terraform-provider-signalfx/blob/master/signalfx/notifications.go#L205

```
case WebhookNotificationType:
		if len(parts) != 4 {
			errs = append(errs, fmt.Errorf("Invalid Webhook notification string, please consult the documentation (not enough parts)"))
			return
		}
		_, err := url.ParseRequestURI(parts[3])
		if err != nil {
			errs = append(errs, fmt.Errorf("Invalid Webhook URL %q", parts[2]))
			return
		}
```

We should probably not require 4 parts if they provide `credentialId`, since the rest of the parts are ignored if you do.

**Comment by cory-signalfx** [comment]
Hey @shwin! Could you look over #129 and pass along any feedback?

**Comment by cory-signalfx** [comment]
Closing this as I plan to ship a new provider today with #129 in it!

**Comment by cory-signalfx** [comment]
Should go out today!
