### ISSUE TITLE
Typos in AWS integration docs

### ISSUE THREAD

**Issue by nickchappell** [splunk-terraform/terraform-provider-signalfx#132]
`website/docs/r/aws_token_integration.html.markdown`, line 26 and `website/docs/r/aws_integration.html.markdown`, line 27, are missing the words that `website/docs/r/aws_external_integration.html.markdown`, line 27 has to complete the sentence in the comments.

**Comment by cory-signalfx** [comment]
Thanks, and done! Fixes will be out soon, once Hashi builds someone's provider. :)
