### ISSUE TITLE
signalfx_data_link does not support Epoch (seconds) time format

### ISSUE THREAD

**Issue by kpainter-atl** [splunk-terraform/terraform-provider-signalfx#149]
In the SignalFX UI you can choose between either epoch seconds or milliseconds as your time format, however the provider only accepts `ISO8601` and `Epoch` which defaults to milliseconds.
<img width="429" alt="Screen Shot 2020-02-21 at 12 51 21 pm" src="https://user-images.githubusercontent.com/52432058/74996946-0b0f9c00-54a9-11ea-8993-debe9bce18d5.png">

**Comment by cory-signalfx** [comment]
Thanks for flagging @kpainter-atl. I'm waiting on some other PRs, but will get a release out as soon as I can!

**Comment by cory-signalfx** [comment]
This should be out in the world now!
