### ISSUE TITLE
Couple issues with the terraform data_links( couldn't get the property name in the UI ) after successful plan and apply.

### ISSUE THREAD

**Issue by saikrishna547** [splunk-terraform/terraform-provider-signalfx#150]
Could get the property name in the UI for the below code or for any of the code, It could get the property value even showing us in the terraform plan and also apply.

resource "signalfx_data_link" "mydatalink_overview_1" {
  context_dashboard_id = "${signalfx_dashboard.overview.id}"
  property_name = "AWSUniqueId"
  target_signalfx_dashboard {
    is_default = true
    name = "Overview awsuniqueid to host dashboard"
    dashboard_group_id = "${signalfx_dashboard_group.xyz_dashboard_group.id}"
    dashboard_id = "${signalfx_dashboard.host.id}"
  }
}

<img width="766" alt="Screen Shot 2020-02-21 at 9 47 27 AM" src="https://user-images.githubusercontent.com/44275490/75062422-9d0ea900-5497-11ea-9862-22258531a44c.png">
<img width="621" alt="Screen Shot 2020-02-21 at 9 47 42 AM" src="https://user-images.githubusercontent.com/44275490/75062431-a1d35d00-5497-11ea-8f08-5305acf4ece2.png">
<img width="1021" alt="Screen Shot 2020-02-21 at 9 48 14 AM" src="https://user-images.githubusercontent.com/44275490/75062452-ab5cc500-5497-11ea-977a-1de643ea0e47.png">

**Comment by cory-signalfx** [comment]
Hrm, something is definitely fishy here. I'm investigating now!

**Comment by ghost** [comment]
@cory-signalfx I'm already working on this one that came in internally.

**Comment by saikrishna547** [comment]
Hi Looks like I am still facing this issue, Is this resolved? can you cross-check?

**Comment by cory-signalfx** [comment]
Hey @saikrishna547, if you update to the latest version of the provider this should be fixed. If not, please let us know!

**Comment by saikrishna547** [comment]
Can I know what's the updated version of sfx provider?

**Comment by cory-signalfx** [comment]
Yup, in [4.14.0](https://github.com/terraform-providers/terraform-provider-signalfx/blob/master/CHANGELOG.md#4140-february-25-2020).
