### ISSUE TITLE
Error when creating couple data_links through terraform for a same dashboard_id and same context_dashboard_id with the different property_name ( which is not expected behavior )

### ISSUE THREAD

**Issue by saikrishna547** [splunk-terraform/terraform-provider-signalfx#151]
Why can't we create 2 data_links with the different property_name and having same context_dashboard_id and dashboard_id(target dashboard) saying "Cannot create multiple cross links for the same property value combination" ( which is not the expected behavior )

Code 1)

```
resource "signalfx_data_link" "mydatalink_overview_1" {
  context_dashboard_id = "${signalfx_dashboard.overview.id}"
  property_name = "AWSUniqueId"
  target_signalfx_dashboard {
    is_default = true
    name = "Overview awsuniqueid to host dashboard"
    dashboard_group_id = "${signalfx_dashboard_group.xyz_dashboard_group.id}"
    dashboard_id = "${signalfx_dashboard.host.id}"
  }
}
```
Code 2)
```
resource "signalfx_data_link" "mydatalink_overview_6" {
  context_dashboard_id = "${signalfx_dashboard.overview.id}"
  property_name = "host"
  target_signalfx_dashboard {
    is_default = true
    name = "Overview containerID data link to Docker Container dashboard"
    dashboard_group_id = "${signalfx_dashboard_group.xyz_dashboard_group.id}"
    dashboard_id = "${signalfx_dashboard.host.id}"
  }
}
```

These things can be created in UI manually, but not in terraform ( which is not right for anyone, we can have to different properties leading to a same dashboard from the same context_dashboard).

**Comment by cory-signalfx** [comment]
Hey @saikrishna547, this doesn't look like a problem within Terraform to me, as I'm able to create data links using your provided examples (i.e. two links with the same targets, but different property names). I also double checked the API code that verifies and agree that it does work!

I suspect you've either got another definition elsewhere in your Terraform or someone has created a data link in the UI that is not governed by Terraform. Keep in mind that the API does not differentiate between assets created with Terraform and those made by hand!

**Comment by cory-signalfx** [comment]
This is (perhaps confusingly) a dupe of #150 

I believe this was a bug wherein the property name wasn't be set!
