### ISSUE TITLE
chart_id in the documentation for the dashboard definition 

### ISSUE THREAD

**Issue by kateetak** [splunk-terraform/terraform-provider-signalfx#152]
**Summary**
The https://www.terraform.io/docs/providers/signalfx/r/dashboard.html documentation provides the following example when referincing a `chart_id`:
`chart_id = "${signalfx_time_chart.mychart0.id}"`

However, when using the `Terraform v0.12.21` and the `provider.signalfx v4.13.0`, a "deprecated warning" is returned when running a `terraform plan` or `terraform apply`.

**Expected Results**
When following the documentation using the latest versions of the provider and terraform, no warnings are returned.

**Actual Results**
The following warning is shown:
```
Warning: Interpolation-only expressions are deprecated

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.
```

**Comment by kateetak** [comment]
Happy to fix it myself, but I wanted to be sure my understanding was correct and we are happy to change the doc at this stage.

There are probably more cases where this could be improved but I was testing this specific one today.

**Comment by cory-signalfx** [comment]
Hey @kateetak! As the warning tells us, this is till valid syntax in versions of Terraform < 0.12. There are still a number of folks who use this version, so this isn't really a bug. But we may as well update them, so I've done so in #153. Thanks for flagging!

**Comment by kateetak** [comment]
Thanks @cory-signalfx !
