### ISSUE TITLE
[New Feature] New resource signalfx_webhook_integration

### ISSUE THREAD

**Issue by xp-1000** [splunk-terraform/terraform-provider-signalfx#157]
Hello, 

Could be cool to be able to configure the generic webhook integration with terraform.

**Comment by cory-signalfx** [comment]
Done in #158 and should be available for you later today when hashi does a build. Thanks for the ping!

**Comment by xp-1000** [comment]
Hello @cory-signalfx 
you are awesomely fast ! thanks for that
https://github.com/terraform-providers/terraform-provider-signalfx/pull/159
