### ISSUE TITLE
Some missing pieces or errors in detectors documentation

### ISSUE THREAD

**Issue by xp-1000** [splunk-terraform/terraform-provider-signalfx#165]
Hello,

Reading the documentation from https://www.terraform.io/docs/providers/signalfx/r/detector.html I believe I have detected some errors (i.e. missing count) but I could be wrong, you will tell me in the PR.

**Comment by xp-1000** [comment]
Here is the PR: https://github.com/terraform-providers/terraform-provider-signalfx/pull/166

**Comment by cory-signalfx** [comment]
Thanks, merged!
