### ISSUE TITLE
Always authenticationrequired on Windows 

### ISSUE THREAD

**Issue by ghost** [splunk-terraform/terraform-provider-signalfx#178]
I'm stuck using the Terraform (v0.12.24) SFX provider on Windows (.terraform\plugins\windows_amd64\terraform-provider-signalfx_v4.18.3_x4.exe) always getting the same error message **authenticationrequired** when trying to create a team. I'm using my user API token and I'm administrator. The same stuff does work when executed on Linux.

Execution on Windows outputs

```
terraform apply -var="access_token={UserAPIToken}" -var="realm=eu0"

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # signalfx_team.team0 will be created
  + resource "signalfx_team" "team0" {
      + id   = (known after apply)
      + name = "Best Team Ever"
      + url  = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

signalfx_team.team0: Creating...

Error: Post https://api.eu0.signalfx.com/v2/team: authenticationrequired

  on main.tf line 14, in resource "signalfx_team" "team0":
  14: resource "signalfx_team" "team0" {
```

Execution on Linux prints this

```
terraform apply -var="access_token={Same UserAPIToken As Above}" -var="realm=eu0"

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # signalfx_team.team0 will be created
  + resource "signalfx_team" "team0" {
      + id   = (known after apply)
      + name = "Best Team Ever"
      + url  = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

signalfx_team.team0: Creating...
signalfx_team.team0: Creation complete after 0s [id=ETyG4c9AEAA]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by cory-signalfx** [comment]
Hey @sebastianf1! Can you provide the section of your terraform config where you're specifying the provider's arguments. Something like:
```
provider "signalfx" {
  auth_token = "${var.access_token}"
}
```

**Comment by cory-signalfx** [comment]
Also you might want to check the following places where the provider will look for credentials (and that might differ on your machines):
* `/etc/signalfx.conf`
* `~/.signalfx.conf`
* the `NETRC` environment variable
* `~/.netrc` on Linux and `~/_netrc` on Windows

The `auth_token`  from the provider should be the highest priority, but these others might be causing a value to be set if your variable isn't working correctly. That's why I asked for the config.

If there was no `auth_token` we should definitely see an error though, so something fishy here!

**Comment by ghost** [comment]
The Terraform script I'm calling is pretty basic (see below). This is the command line as I use it: `terraform apply -var="access_token={UserToken}" -var="realm=eu0"`

```
variable "access_token" {
  description = "SignalFx Access Token"
}

variable "realm" {
  description = "SignalFx Realm"
}

provider "signalfx" {
  auth_token = var.access_token
  api_url    = "https://api.${var.realm}.signalfx.com"
}

resource "signalfx_team" "team0" {
  name = "Best Team Ever"
}

```

The files (in my Windows environment) you requested to look for, are not here: none on disk (*netrc*, *signalfx.conf), not set (the NETRC environment variable).

**Comment by cory-signalfx** [comment]
Related, I assume you're using the same token in both places. Be aware that SignalFx user tokens periodically expire and need to be updated. (That it works in Linux means you're using the right one there, and I assume in Windows too, but just in case!)

**Comment by ghost** [comment]
Yes, first I tried in Windows (=fail). After that I tried the same code (same script, same token, same realm) on Linux (=success). After this, I see the same token in my SFX profile. This shows the token used is still valid.

**Comment by cory-signalfx** [comment]
Marvelous, thanks for checking!

* There is a newer release of the provider, but the only change is the addition of some timeout code which should not affect you. (But you can upgrade just to be sure.)
* The [last thing the code does is check for an empty auth token](https://github.com/terraform-providers/terraform-provider-signalfx/blob/master/signalfx/provider.go#L122) so we know _something_ is set there.
* The provider doesn't log the token we'll be using for obvious reasons. We could make a branch that logs the token, but you'd need to compile the binary (`GOOS=windows`). After you replace the one in your `.terraform\plugins\windows_amd64` and run the command again with `TF_LOG=debug`. I dunno if that's feasible for you or not.
* You could MITM proxy the request perhaps.

Thoughts?

**Comment by cory-signalfx** [comment]
Hey @sebastianf1, I just stumbled into an idea.

If you do a `terraform plan -out $somefile` then you can see the token in there. Notably by doing something like `terraform show -json $somefile | jq` and looking for the `variables` section. Maybe this will help?

**Comment by ghost** [comment]
Currently it looks to me like another company proxy issue *ARGH* I checked the proxy environment variables HTTP_PROXY, HTTPS_PROXY, NO_PROXY, but no difference to the Linux setup.

**Comment by cory-signalfx** [comment]
Yuck! I'll leave this here for a while in case you find something that I can do to help?

**Comment by cory-signalfx** [comment]
Timing out, hope it's working!
