### ISSUE TITLE
 Publish GitHub releases during provider releases

### ISSUE THREAD

**Issue by pdecat** [splunk-terraform/terraform-provider-signalfx#179]
Hi,

releases are currently published by updating the changelog, pushing a binary, and making a GitHub "tag" release.
Users can't subscribe to these releases automatically, though: https://github.community/t5/How-to-use-Git-and-GitHub/Not-getting-release-notification-despite-quot-Watching-releases/td-p/19665.

It would be awesome to publish rich releases on GitHub, allowing users to subscribe.

Several other official providers do this already:
- [Azure](https://github.com/terraform-providers/terraform-provider-azurerm/releases)
- [AWS](https://github.com/terraform-providers/terraform-provider-aws/releases)
- [Google](https://github.com/terraform-providers/terraform-provider-google/releases)
- [Helm](https://github.com/terraform-providers/terraform-provider-helm/releases)
- [Kubernetes](https://github.com/terraform-providers/terraform-provider-kubernetes/releases)

**Comment by cory-signalfx** [comment]
An excellent suggestions @pdecat! `git tag -m` it shall be from now on. I will leave this open as a reminder. :)

**Comment by cory-signalfx** [comment]
Because Hashi tags the repo this requires someone to remember to go and edit the release by hand. I'll keep doing this, but expect me to forget sometimes. :(

**Comment by pdecat** [comment]
I believe that's managed by hashicorp's Teamcity CI.

It probably needs some configuration updates.

**Comment by cory-signalfx** [comment]
Yeah, they said it was a manual process on their end, which I assume they don't mind the effort for on big repos. They said it's possible to automate, but I get the impression they want to continue investing in us owning the process before fixing those bits. (There's some plan to give us control in the future.)
