### ISSUE TITLE
Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by davisliu11** [splunk-terraform/terraform-provider-signalfx#199]
Terraform version: 0.12.13
Signalfx provider version: 4.10.2

When I create SignalFx chart using dynamics as below, I keep on getting this error "Error: Provider produced inconsistent final plan" sometimes. 
```
locals {
  my_modules = [
    module.a,
    module.b,
    module.c,
  ]
}

resource "signalfx_dashboard" "my_dashboard" {
  name            = "my dashboard"
  dashboard_group = "${signalfx_dashboard_group.my_dashboard_group.id}"

  time_range = "-4h"

  dynamic "chart" {
    iterator = chart_id
    for_each = compact([for mod in local.my_modules : mod.output_chart_id])

    content {
      chart_id = chart_id.value
      width    = 6

      column = 6 * (chart_id.key % 2)
      row    = floor(chart_id.key / 2)
    }
  }
}
```

Here is the error.
```
Error: Provider produced inconsistent final plan

When expanding the plan for signalfx_dashboard.experience_success to include
new values learned so far during apply, provider "signalfx" produced an
invalid new value for .chart: block set length changed from 1 to 3.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: exit code from docker is 1
```

Command to apply is as below. (I have removed some personal info)
```
docker run -u root --entrypoint /tf/0.12.13/terraform -e TF_VAR_signalfx_auth_token -e TF_WARN_OUTPUT_ERRORS --rm -it -w /app/ -v /mypath/signalfx:/app  terraform_docker_image:latest apply -refresh=false -parallelism=1
```

**Comment by cory-signalfx** [comment]
Thanks for sending this along. I have no idea what it means, so I'll do some digging. :)

**Comment by cory-signalfx** [comment]
I can confirm that is this reproducible with current versions of both Terraform and the provider.

**Comment by cory-signalfx** [comment]
This issue is the same as [this issues in the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/issues/10107) and has the same quality that a second `apply` fixes the problem.

I'm asking around within the HashiCorp Terraform channel. More later!

**Comment by cory-signalfx** [comment]
Update that I didn't get any response on this, will try again today.

**Comment by cory-signalfx** [comment]
Hey @davisliu11, thanks for the patience! After asking around I was told this issue is related to [Terraform #24697](https://github.com/hashicorp/terraform/pull/24697) and that when it lands in 0.13 it should fix the issue. In the meantime, this is **not** a provider issue ( 😄) and you can just run `apply` again and it will clear up.

Thanks for reporting!
