### ISSUE TITLE
`signalfx_azure_integration` services field is now required

### ISSUE THREAD

**Issue by Shr3ps** [splunk-terraform/terraform-provider-signalfx#202]
Since release `v4.19.0`, the `services` field is now mandatory, which means we need to list every Azure services we want to monitor with SignalFX.
This list seems outdated on the documentation page: https://www.terraform.io/docs/providers/signalfx/r/azure_integration.html#service-names

Can you:
- update the documentation with the exhaustive list of Azure services available or compatible?
- update the terraform provider to handle the option "all services"? It might be the default behavior when this field is `null` or maybe you can handle the special string "*": `services = ["*"]`.

**Comment by pdecat** [comment]
Note: [changelog incorrectly references](https://github.com/terraform-providers/terraform-provider-signalfx/blame/v4.19.7/CHANGELOG.md#L46) https://github.com/terraform-providers/terraform-provider-signalfx/pull/188 instead of https://github.com/terraform-providers/terraform-provider-signalfx/pull/189

**Comment by pdecat** [comment]
Having a datasource to get the list of integration services could help working around this issue:

https://github.com/terraform-providers/terraform-provider-signalfx/blob/v4.19.7/signalfx/resource_signalfx_azure_integration.go#L182

**Comment by cory-signalfx** [comment]
Oh, having a data source is a really good suggestion @pdecat. Thanks!

**Comment by cory-signalfx** [comment]
Data source added in #204

**Comment by pdecat** [comment]
> Data source added in #204

Thanks @cory-signalfx, that was fast!

May I suggest doing the same for GCP?

The supported GCP services seem to be listed there: https://github.com/signalfx/signalfx-go/blob/v1.6.34/integration/model_gcp_integration.go#L30

**Comment by cory-signalfx** [comment]
Oh, yes! I feel dumb for having forgotten that. 😛
