### ISSUE TITLE
Dashboard creation too slow since 4.19

### ISSUE THREAD

**Issue by MartinTeeVarga** [splunk-terraform/terraform-provider-signalfx#208]
I am creating dashboards with over 30 graphs. This used to take about 2s per dashboard. Since v4.19 it takes 37s. I am unable to add more graphs to a dashboard because at some point I get HTTP 504 from the server (which used to be OK before). Example below:

```
resource "signalfx_dashboard_group" "group0" {
  name = "Example Dashboard Group"
}

resource "signalfx_dashboard" "dashboard0" {
  name = "Example Dashboard"
  dashboard_group = signalfx_dashboard_group.group0.id

  column {
    width = 12
    height = 1
    column = 0
    chart_ids = signalfx_text_chart.text0.*.id
  }
}

resource "signalfx_text_chart" "text0" {
  count = 60
  name  = "Text"

  markdown = <<-EOF
    Hello world
  EOF
}
```
Verified with 4.21, same issue.

**Comment by cory-signalfx** [comment]
Hrmmm, odd. I am a bit busy the next day or two, but I will do some extra testing here to try and isolate this as soon as I can. I can't think of why it got slower on this end (i.e. in the provider) but perhaps some of the HTTP tuning caused problems.

**Comment by saikrishna547** [comment]
I agree with @MartinTeeVarga  i am also facing the same issue. I think I have already mentioned this on one of  the issue i opened.

**Comment by cory-signalfx** [comment]
Hey folks, I'm around to doing some more digging today. Serendipitously @pdecat contributed #211 which might shed some light on this, or at least (in)validate my mental model of how changes since 2.19 have affected things.

**Comment by cory-signalfx** [comment]
Alright, I've done some tests locally this morning with a large dashboard in `HEAD` and got:

`signalfx_dashboard.mydashboard0: Creation complete after 39s [id=EZHg7BvAYAA]`

I then switch to v4.18.6 and ran the same test:

`signalfx_dashboard.mydashboard0: Creation complete after 3s [id=EZHhtBgAYAI]`

So I guess I have some digging to do.

**Comment by cory-signalfx** [comment]
Specifically, this came up between v4.19.0 and v4.19.1

**Comment by cory-signalfx** [comment]
Can verify there is no difference in the HTTP bodies between the two versions.

**Comment by cory-signalfx** [comment]
Alright, I've finally tracked this down to something on the API side. This is *not* the Terraform provider's fault but that's not really important here since it impacts your work either way. There was an internal issue filed for this previously, it's now been updated and increased in priority.

**Comment by mobeigi** [comment]
Hey @cory-signalfx , how are you doing? :) 

Is there an update on this issue? I would like to update my provider version to fix the #148 bug but if I do I introduce this new performance bug. There is no build in between where there is no performance loss and has the bug fix.

Thank you!

**Comment by cory-signalfx** [comment]
Hey @mobeigi! I'm doing pretty well. :)

There should be no difference in performance between versions of the provider. The regression is API side. I've been able to reproduce the problem with all versions of the provider, and it only affects dashboards with larger numbers of charts.

**Comment by mobeigi** [comment]
@cory-signalfx I don't experience that personally. In my tests below the speed is almost twice as slow going from a fresh `terraform init` state and timing the plan and apply. The plan is speedy but the API calls to apply are slow. These are the exact same dashboards being applied both times with the only change being the `tf` version and `provider` version.

Does the change in terraform version have anything to do with it?

From my quick testing:
-------

Old Terraform Version: **0.12.24**
Old Terraform Provider Version: **4.18.6**

```
gtime sh -c 'terraform plan && terraform apply --auto-approve'
Apply complete! Resources: 150 added, 0 changed, 0 destroyed.
0.28user 0.37system 0:26.21elapsed 2%CPU (0avgtext+0avgdata 22440maxresident)k
0inputs+0outputs (27major+23159minor)pagefaults 0swaps
```

New Terraform Version: **0.12.26**
New Terraform Provider Version: **4.23.1**

```
gtime sh -c 'terraform plan && terraform apply --auto-approve'
Apply complete! Resources: 150 added, 0 changed, 0 destroyed.
0.26user 0.35system 0:52.90elapsed 1%CPU (0avgtext+0avgdata 22276maxresident)k
0inputs+0outputs (25major+23058minor)pagefaults 0swaps
```

**Comment by cory-signalfx** [comment]
Well, that's annoying. We've reproduced it locally and it's _definitely_ on the server/API side. We even know why! There's nothing about Terraform to my knowledge that cares one way or the other.

Your test, however, begs to differ. Lemme do some fiddling this morning and see if I missed something? (Perhaps I was too excited by finding the regression on the API-side?)

**Comment by cory-signalfx** [comment]
Sooo, good news is #221 seems to fix this for me. Bad news is I don't understand why. I've had a look over the source and nothing makes sense. Before I merge and release this I wanna ask around internally…

**Comment by cory-signalfx** [comment]
Releasing today as `v4.23.2`
