### ISSUE TITLE
Possibility to have the credentialId as output from signalfx_slack_integration

### ISSUE THREAD

**Issue by dogmatic69** [splunk-terraform/terraform-provider-signalfx#216]
As per the title, currently we need to provision the integration in terraform and then get the ID from the UI in signalFX to be able to then reference the integration in other places

Ideally: (if there was an output for `signalfx_slack_integration.team.credentialId`)

```
resource "signalfx_slack_integration" "team" {
    name = "Slack - My Team"
    enabled = true
    webhook_url = "http://example.com"
}

resource "signalfx_detector" "failure-topic-alert" {
    name = "failure-topic-alert"
    description = "Detector for messages received on the failure topic"
    max_delay = 30
    program_text = "..."
    rule {
        description = "Alert if message received on the failure topic"
        severity = "Critical"
        detect_label = "Message received on the failure topic"
        notifications = ["Slack,${signalfx_slack_integration.team.credentialId},channel-name"]
    }
}
```

**Comment by cory-signalfx** [comment]
Hey @dogmatic69! This works today, here's the syntax:

```
notifications = ["Slack,${signalfx_slack_integration.team.id},channel-name"]
```

The credential ID is just the integration's ID, which is already present!

**Comment by dogmatic69** [comment]
Perhaps the terraform docs for the provider need to be updated? According to the docs there are no outputs for the `signalfx_slack_integration` module.

**Comment by cory-signalfx** [comment]
Sure, I checked around and see that a couple of providers document this. On it!

**Comment by cory-signalfx** [comment]
Merged and sent along for website updates, which Hashi does periodically through the day. Thanks @dogmatic69!
