### ISSUE TITLE
Importing V1 Detectors

### ISSUE THREAD

**Issue by dexterleng** [splunk-terraform/terraform-provider-signalfx#219]
I would like to be able to import detectors created from the UI (v1 API). Is there a reason not to support it? Otherwise I would love to be able to help.

**Comment by cory-signalfx** [comment]
The V1 API is *very* different from the V2 API, as it was used exclusively with the SignalFx UI. There are no plans to add support for this in Terraform.

I believe that conversions are being planned for SFx customers, so maybe ping your sales contact or support and ask. They should be able to do this for you!
