### ISSUE TITLE
allow transient muting rules

### ISSUE THREAD

**Issue by JSDevine** [splunk-terraform/terraform-provider-signalfx#222]
Hi, 

I'm trying to set up transient muting rules IE when a new version of the application is deployed via terraform, I want to create muting rule that lasts for 15mins. 
This will prevent known alerts during deployments - that otherwise should be responded to, without the need to manually add muting rules into SFX before the deployment. 

The issue is that on subsequent applies, TF attempts to delete the rule (new resource forced due to change in start/end time)
but it will then return:

`1 error occurred:
        * signalfx_alert_muting_rule.test_mute (destroy): 1 error occurred:
        * signalfx_alert_muting_rule.test_mute: Unexpected status code: 400: {
  "code" : 400,
  "message" : "Cannot delete alert muting in the past."
}
`

I understand to couple the TF resource to the alert ID, but could an option be added to the resource to allow transient alerts? IE create a new muting rule and update the ID without destroying? 

As otherwise, the only way i can see to accomplish this is either:
a) using a null resource in TF that sends a request to the SFX API. 
b) edits the TF state file to remove the resource there and allow TF to recreate 

neither of which is an ideal solution. 

https://github.com/terraform-providers/terraform-provider-signalfx/blob/master/signalfx/resource_signalfx_alert_muting_rule.go

**Comment by cory-signalfx** [comment]
Hey @JSDevine!

Seems like you're clashing with both the Terraform and SignalFx API ways of doing things here. Both have good reasons for being difficult in this case and I'm not really keen to try and pick either apart. Terraform wants to manage entities with identities and the SignalFx API wants to keep alert mutes in the past firmly rooted there.

My suggestion in this case be one of the following:
* Add a term to the alert that watches for a deploy metric (e.g. services.deployed=1, with a service dimension) and add it as a condition (i.e. only alert when threshold is violated **and** servies.deploy is < 1 max last 15 minutes)
* Make an API call outside of Terraform to instantiate an alert muting rule

This avoids Terraform trying to manage a fleeting rule and allows the SignalFx API to operate with either transient mutes or a compound alert.
