### ISSUE TITLE
Adding tag support to resources

### ISSUE THREAD

**Issue by MovieStoreGuy** [splunk-terraform/terraform-provider-signalfx#228]
I think I have had a conversation in the past with @cory-signalfx regarding this, but I wanted to have an issue that I could reference.

I want to be able to add tags to resources (using detectors as an example, https://developers.signalfx.com/detectors_reference.html#operation/Create%20Single%20Detector) which would enable automated resource enforcement. 

My memory is that this couldn't be done due to tags being eventually consistent but I would like to confirm this as to why this hasn't been added.

**Comment by cory-signalfx** [comment]
Hey @MovieStoreGuy, you have indeed had that conversation and you are correct. The issue being that the provider can't trust that the response will have the tags in it. :(

If you raise this with support and tell them how important it is, it's helpful to me. Customer needs outweigh "Cory says this would be good for Terraform". 😄
