### ISSUE TITLE
Single Value Chart with Secondary Visualization "Sparkline"

### ISSUE THREAD

**Issue by venkat240042** [splunk-terraform/terraform-provider-signalfx#243]
I have been trying to  Single chart with Secondary visualization with Sparkline  with show_spark_line = true   using terraform script. For some reason not accepting show_spark_line with secondary  visualization. Could you please take a look into my script and share inputs to resolve error
Error: Unexpected status code: 400: {
  "code" : 400,
  "message" : "Cannot use Show Sparkline with Secondary Visualization Option"
}

Script: 
resource "signalfx_single_value_chart" "throughput" {
  color_by                = "Scale"
  description             = "Represents the throughput of the ${var.app_name} service"
  is_timestamp_hidden     = false
  max_delay               = 0
  max_precision           = 5
  name                    = "Throughput - ${var.chart_name}"
  program_text            = <<-EOF
        A = data('requests.count', filter=filter('app', '${var.app_name}') and filter('env', '${var.env_name}'), rollup='delta').sum().sum(over='14d').publish(label='A')
    EOF
  secondary_visualization = "Sparkline"
  show_spark_line         = true
  unit_prefix             = "Metric"
  color_scale {
    color = "green"
    lte   = var.app_throughput
  }
  color_scale {
    color = "red"
    gt    = var.app_throughput
  }
  viz_options {
    display_name = "A"
    label        = "A"
    color        = "green"
  }
}
output "id" {
  value = signalfx_single_value_chart.throughput.id
}

**Comment by keitwb** [comment]
Hi @venkat240042 can you try just setting `secondary_visualization` and omitting `show_spark_line`?  I have confirmed that the backend is rejecting those two together, as I believe `show_spark_line` is a legacy option.

**Comment by venkat240042** [comment]
Hi Splunk-Terraform/Terraform-Provider-Signalfx,
Yes, Terraform script is working without any error by setting
secondary_visualization
= "Sparkline" and show_spark_line = fasle, however this doesn't give the
secondary visualization spark line
[image: image.png]

**Comment by keitwb** [comment]
Ok great. Let us know if you have any more issues.
