### ISSUE TITLE
Update documentation for Team(s)

### ISSUE THREAD

**Issue by nigeldunn** [splunk-terraform/terraform-provider-signalfx#245]
The documentation no longer matches the API for how teams are used in 5.0.0 in resource_signalfx_detector.
Currently it says:
![image](https://user-images.githubusercontent.com/176692/93051401-bf704a00-f6a7-11ea-8720-da7d595a134c.png)

However this is not true.

**Comment by ImDevinC** [comment]
This same issue applies to `signalfx_dashboard_group`
