### ISSUE TITLE
New dashboards/detectors implementation is a degradation from previous integrations

### ISSUE THREAD

**Issue by ImDevinC** [splunk-terraform/terraform-provider-signalfx#250]
>BREAKING CHANGES:
>
> - resource/dashboard_group: The field teams have been removed, please use the team resource's dashboard_groups >argument. #244
>- resource/detector: The field teams has been removed, please use the team resource's detectors argument. #244

https://github.com/splunk-terraform/terraform-provider-signalfx/releases/tag/v5.0.0

This implementation is extremely limiting for larger projects. For example, we keep our dashboards, charts, and detectors for each of our applications in the repository with the application code so that when we deploy application updates, the proper signalfx configuration gets deployed as well. Before we could easily just attach a team ID to these resources as well, and they would all show up under the proper teams configuration. 

With this new integration, any time we add a new dashboard or detector, we have to output the resource and then redeploy our team reference as well (stored in another repository). This adds significant overhead and complexity to the process and I would ask that this please be reviewed. We have also opened a support case with our TAM explaining this.

**Comment by jrcamp** [comment]
Thanks for detailing your use case, it definitely helps. This was done due to the API breaking backwards compatibility for these resources. I will look into it more to see if there's a better solution.

**Comment by jrcamp** [comment]
@ImDevinC @RafeKettler

What do you think about a new resource `signalfx_team_links` that allows to do linking to detectors and dashboard groups? For example:

```terraform
resource "signalfx_team_links" "teamProdLinks" {
   team = "team_id"
   dashboard_groups = ["dashboard_group_id1", "dashboard_group_id2"]
   detectors = ["detector_id1", "detector_id2"]
}
```

**Comment by ImDevinC** [comment]
If we can use multiple team links from different repos, pointing to the same team, this should work great. Below is an example usage scenario

**Repo One**
```
resource "signalfx_team_links" "first_links" {
   team = "my_first_team_id"
   dashboard_groups = ["dashboard_group_id1"]
   detectors = ["detector_id1"]
}
```

**Repo Two**
```
resource "signalfx_team_links" "second_links" {
   team = "my_first_team_id"
   dashboard_groups = ["dashboard_group_id2"]
   detectors = ["detector_id2"]
}
```

**Comment by jrcamp** [comment]
Yep multiple will work.

**Comment by tommynguyen-vungle** [comment]
> If we can use multiple team links from different repos, pointing to the same team, this should work great. Below is an example usage scenario
> 
> **Repo One**
> 
> ```
> resource "signalfx_team_links" "first_links" {
>    team = "my_first_team_id"
>    dashboard_groups = ["dashboard_group_id1"]
>    detectors = ["detector_id1"]
> }
> ```
> 
> **Repo Two**
> 
> ```
> resource "signalfx_team_links" "second_links" {
>    team = "my_first_team_id"
>    dashboard_groups = ["dashboard_group_id2"]
>    detectors = ["detector_id2"]
> }
> ```

Hi @jrcamp, so at our company, we face similar issue as @ImDevinC. We have 100+ detectors, each of them links to respective teamID. Is it better to have the structure like this:

```hcl
resource "signalfx_detector" "sample_detector"  {
  detector_group_id = ""
}

resource "signalfx_detector_group" "sample_detector_group"  {
}

resource "signalfx_team_links" "teamProdLinks" {
   team = "team_id"
   dashboard_groups = ["dashboard_group_id1", "dashboard_group_id2"]
   detector_groups = ["detector_group_id1", "detector_group_id2"]
}
```

In this case, the `detector` & `detector_group` has similar relationship as `dashboard` & `dashboard_group`. And we could avoid the burden of adding new detector_id to `signal_team_links` every time we create a new one. What do you think?
