### ISSUE TITLE
Upgrade to SDK v2

### ISSUE THREAD

**Issue by jrcamp** [splunk-terraform/terraform-provider-signalfx#251]
We're currently on v1.15 of the SDK and there's a v2 that requires a number of changes: https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html

There's a migrator to help with it: https://github.com/hashicorp/tf-sdk-migrator

Haven't seen anything indicating how long v1 support will be maintained.

**Comment by xp-1000** [comment]
why closing this @luke-sterkowicz ? it seems not resolved

**Comment by luke-sterkowicz** [comment]
sorry, my mistake
