### ISSUE TITLE
tags and customProperties for detector resource

### ISSUE THREAD

**Issue by xp-1000** [splunk-terraform/terraform-provider-signalfx#254]
Hello,

This could be very nice to have the `customProperties` and `tags` api fields configurable in terraform detector resource : 

https://developers.signalfx.com/detectors_reference.html#operation/Create%20Single%20Detector

**Comment by atoulme** [comment]
I have opened https://ideas.splunk.com/ideas/SFXIMMID-I-622 to follow up on this request. Tags support was implemented, but customProperties seem to still be missing.
