### ISSUE TITLE
Order of the filter overrides and dashboards

### ISSUE THREAD

**Issue by mcmiv413** [splunk-terraform/terraform-provider-signalfx#256]
Is there anyway to control the order that the filter overides show up on top as well as the order of the dashboards in the group?

I followed the suggestion here:

https://github.com/splunk-terraform/terraform-provider-signalfx/issues/127 

Originally I had broken my stuff out into different files, based on what was suggested in the above I pulled it all into a single file for a dashboard group but it made no difference. On the positive side it doesn't seem to "fix" it if I reorder it after so I may be able to work around some of this with mirrored dashboards.

**Comment by atoulme** [comment]
Closing this issue as unplanned. If this issue is still relevant, please reopen the issue.
