### ISSUE TITLE
Set viz_options "Entries with missing data" to Hide in list chart

### ISSUE THREAD

**Issue by myuwono** [splunk-terraform/terraform-provider-signalfx#262]
Would be great to be able to set this viz_options in terraform

![image (12)](https://user-images.githubusercontent.com/15880686/98171103-4a045580-1f43-11eb-8ac2-bda1ed27fc88.png)

**Comment by atoulme** [comment]
Closing this issue as unplanned. If this issue is still relevant, please reopen the issue.
