### ISSUE TITLE
signalfx_aws_integration: Add support for metricStatsToSync option

### ISSUE THREAD

**Issue by ericdahl** [splunk-terraform/terraform-provider-signalfx#272]
We're currently utilizing the `metricStatsToSync` option to pull in additional percentile metrics for ALBs that would otherwise not be ingested into SignalFX, via configuration like:

```json
  "metricStatsToSync": {
    "AWS/ApplicationELB": {
      "TargetResponseTime": [
        "p95",
        "upper",
        "lower",
        "sum",
        "count",
        "mean"
      ]
    }
  },
```

It seems like the Terraform provider does not support this

Documentation for this is at https://dev.splunk.com/observability/docs/integrations/aws_integration_overview/#Specify-AWS-statistics

It would be great if this feature could be added

**Comment by narmendariz** [comment]
Opened feature request FEED-3764 for this
