### ISSUE TITLE
Problem with time_chart and axis in viz_options

### ISSUE THREAD

**Issue by doctornkz** [splunk-terraform/terraform-provider-signalfx#278]
Good day!

I am using that resource in terraform:
```
resource "signalfx_time_chart" "sfx-XXX" {
  name              = "Network Usage Per Node"
  description       = "bytes in + bytes out per pod, summed per node"
  plot_type         = "LineChart"
  stacked           = false
  axes_include_zero = true
  
  legend_options_fields {
    property = "sf_originatingMetric"
    enabled  = true
  }
  viz_options {
    label        = "B"
    color        = "blue"
    axis         = 1
    display_name = "Tx (bytes/sec)"
  }

  program_text              = <<EOF
A = ####### SKIPPED ########

EOF
  disable_sampling          = false
  minimum_resolution        = 0
  unit_prefix               = "Binary"
  max_delay                 = 0
  color_by                  = "Dimension"
  on_chart_legend_dimension = ""
  time_range                = 900
}
```
Terraform complains with this output:
```
Error: expected viz_options.0.axis to be one of [left right], got 1

  on sfx_test.tf line 899, in resource "signalfx_time_chart" "sfx-XXX":
 899: resource "signalfx_time_chart" "sfx-XXX" {
```

In that line I see the proper structure : https://github.com/splunk-terraform/terraform-provider-signalfx/blob/main/signalfx/resource_signalfx_time_chart.go#L421 

But if I am using structure from signalfx-go library I am having that one : 
https://github.com/signalfx/signalfx-go/blob/master/chart/model_publish_label_options.go#L28

```
	// Specifies the position of the Y-axis for the plot associated with the SignalFlow statement. If `yAxis` is set to 0, the axis is on the left side; otherwise it's on the right. The default is 0 (left side).<br> **Note** -- This option is only available if 'options.type` is `TimeSeriesChart`, `List`, or `SingleValue`.
	YAxis int32 `json:"yAxis,omitempty"`
```
It gives me an inconsistent code, I can't use String because Go library can't produce proper data structure:
```
# signalfx2terraform/src/utils
src/utils/utils.go:468:18: cannot use "left" (type untyped string) as type int32 in assignment
src/utils/utils.go:469:36: cannot use "right" (type untyped string) as type int32 in assignment
```
...and at the same time API can't apply state with Int32. 

Yes, I can fix it with the custom, overlapping structure, but it's not clear enough. Also we can change `1` to `right` and `0` to `left` after every API export, but it's definitely monkey job. 

Maybe I am doing something wrong? 
Thank you!

**Comment by keitwb** [comment]
@doctornkz can you explain what your `signalfx2terraform` program does?  I assume it is dumping data from our API and turning it into terraform resources?  Is it meant for a one-time migration to terraform or what?

The reason terraform has the string values is to make it more user-friendly and obvious what the values mean, compared to our API that uses numbers.  Since our API came first, the numbers are the original thing.  We could add a new option in terraform called `axisOrig` or something that allowed the numeric value but if all you have to do in your signalfx2terraform code is a simple transformation from 0/1 to "left"/"right" I would be wary of making the terraform provider more complicated just for that.

**Comment by doctornkz** [comment]
@keitwb You exactly got an idea of the tool - user is passing the API token and dashboard/detector ID and getting back  terraform file. We are saving a giant amount of our time with that automation. 

I had this transformation before, but I switched it back to avoid complexitiy and unconsistancy. I need to keep in my head all tricks, wrappers and transformation. Axis it only one example, with colors I have much more fun. I thought that in ideal world the library 
should have the same definition as API for that library.

I don't like the idea about axisOrig, it will add more confusion in community and documentation. I rather will implement overlapping data structure and that's it.
