### ISSUE TITLE
color_by and color_scale options not working for signalfx_single_value_chart

### ISSUE THREAD

**Issue by jhollfelder** [splunk-terraform/terraform-provider-signalfx#284]
The documentation for [signalfx_single_value_chart](https://registry.terraform.io/providers/splunk-terraform/signalfx/latest/docs/resources/single_value_chart#argument-reference) includes information for how to change the color of the displayed value when color_by = "Scale" is selected however this does not seem to be working.

Here is my terraform code snippet that has the problem: 
```
resource "signalfx_single_value_chart" "tfchart_06" {
    name = "p99 Memory TF_JRH"
    description = "99th percentile of Memory utilization"
    program_text = <<-EOF
        A=data("memory.utilization").percentile(99).publish(label="p99-memory")
        EOF
    color_by = "Scale"
    color_scale = [ { gte = 85, color = "red" }, { lt = 85, color = "green" } ]
}
```
The error message I get when I run `terraform plan` is:
```
Error: Unsupported argument

  on main.tf line 79, in resource "signalfx_single_value_chart" "tfchart_06":
  79:     color_scale = [ { gte = 85, color = "red" }, { lt = 85, color = "green" } ]

An argument named "color_scale" is not expected here. Did you mean to define a
block of type "color_scale"?
```
Based on the documentation it looks like my syntax is correct.  The version of Terraform I'm using is 
```
Terraform v0.14.5
+ provider registry.terraform.io/splunk-terraform/signalfx v6.4.0
```
Is the problem on my end or does the documentation need to be updated?  Thank you.

**Comment by jakzo** [comment]
Looks like the docs need to be updated. The [test here](https://github.com/splunk-terraform/terraform-provider-signalfx/blob/c6041ba5f36e51f22b68b63c96650a91d06a9f5c/signalfx/resource_signalfx_single_value_chart_test.go) shows that you should use it like this:

```
color_by = "Scale"
color_scale { gte = 85, color = "red" }
color_scale { lt = 85, color = "green" }
```

**Comment by atoulme** [comment]
Closing this issue as unplanned. If this issue is still relevant, please reopen the issue.
