### ISSUE TITLE
Unable to configure a chart to use IEC Units

### ISSUE THREAD

**Issue by pauljflo** [splunk-terraform/terraform-provider-signalfx#286]
When creating a chart in the Signalfx console under Chart Options > Advanced Options there is a
`Use IEC units` checkbox. 

There does not appear to be away to do this using the Terraform provider which means some charts display incorrect values.

**Comment by atoulme** [comment]
Thanks for this report! I have opened a Splunk idea to continue the conversation. Please feel free to upvote and comment on it:https://ideas.splunk.com/ideas/SFXIMMID-I-623
