### ISSUE TITLE
muting rule config for multiple detectors is inconsistent with the UI

### ISSUE THREAD

**Issue by xp-1000** [splunk-terraform/terraform-provider-signalfx#292]
Hello,

This provider provides an attribute `detectors`: https://registry.terraform.io/providers/splunk-terraform/signalfx/latest/docs/resources/alert_muting_rule#detectors which ease the configuration for the user.

However, the way it works now is not consistent with the UI behavior and capabilities.
Indeed, instead of adding one different filter for each detector in the list, it should probably add only one filter with a list of detectors as value.

in fact the detector link is an UI only feature, this is why there is no any detectors field in api: https://dev.splunk.com/observability/reference/api/incidents/latest#endpoint-update-single-muting-rule

The problem is it was probably not designed to support multiple detectors so even if the current terraform implementation should work it ends by inconsistent information in the UI:

```
{
  "description": "terraform way example",
  "filters": [
    {
      "NOT": false,
      "property": "env",
      "propertyValue": "preprod"
    },
    {
      "NOT": false,
      "property": "sf_detectorId",
      "propertyValue": "Eo8uuKGAIAA"
    },
    {
      "NOT": false,
      "property": "sf_detectorId",
      "propertyValue": "Eo8uuC8AIAA"
    }
],
  "sendAlertsOnceMutingPeriodHasEnded": true,
  "startTime": 1616112000000,
  "stopTime": 1616284800000
}
```

is what terraform does, but if you want do the same in UI you will probably pick up elements from a list of detectors producing the equivalent:

```
{
  "description": "one filter list example",
  "filters": [
    {
      "NOT": false,
      "property": "env",
      "propertyValue": "preprod"
    },
    {
      "NOT": false,
      "property": "sf_detectorId",
      "propertyValue": ["Eo8uuKGAIAA", "Eo8uuC8AIAA"]
    }
],
  "sendAlertsOnceMutingPeriodHasEnded": true,
  "startTime": 1616112000000,
  "stopTime": 1616284800000
}
```

the UI seems to take the first filter (if any) with the property `sf_detectorId` defined with a __string__ value. this UI link seems not enable when there is no any `sf_detectorId` property provided OR if its value is not a string (a list in the example above).

In the first example, the ui feature will be enabled and shows only one detector and mask all others (because when detector link is enabled, `sf_detectorId` properties is not present in muting rule conditions). the only way to know it apply to other monitors is to use the API.

In the second example, the ui feature is not enabled so the `sf_detectorId` is shown as any other properties. It is not as well integrated as with the ui link feature but at least we do not have wrong information.

please consider this comes from an empiric reasoning so there could be errors but I am pretty sure:
- either the UI feature should support multiple detectors (and from a list of different filters to match terraform implementation)
- or terraform provider should define one filter with a list as value to prevent this feature to be enabled: https://github.com/splunk-terraform/terraform-provider-signalfx/blob/main/signalfx/resource_signalfx_alert_muting_rule.go#L107

as workarounds:
- you can create one muting rule per detector with a `for_each`. they will be well integrated in the UI (each muting rule associated to its detector) but you will have "duplicated" and lot of muting rules (if all muting rules are managed by terraform this is not a problem)
- you can create the muting rule without using the `detectors` attribute but defining the list of IDs as value of a filter with the property `sf_detectorId`. you will keep one muting rule as desired in first place but you loose the detector link UI integration. you will also see a list of detectors IDs not understandable (but correct)
- same logic but using the `sf_detector` field instead of `sf_detectorId` has the advantage to be more understandable showing the names of detectors instead of IDs but to be used only if detectors are also in terraform to be sure properties used in muting rules match the last names of detectors resources.

**Comment by luke-sterkowicz** [comment]
The reasoning is valid, although neither of the methods is supported by the UI at the moment (specifying multiple detector IDs as separate filters or as a list for the property value). Listing multiple detector IDs will make the rule obsolete. However, while the API doesn't restrict the filter values I am adding an explicit note in the docs for now, for clarity (will be in the next release). Good suggestion though will be to extend propertyValue onto lists in tf.
