### ISSUE TITLE
Unsupported block type error when using viz_options with signalfx_event_feed_chart resource

### ISSUE THREAD

**Issue by bxtp4p** [splunk-terraform/terraform-provider-signalfx#293]
This looks like maybe a documentation issue. The example on this page https://registry.terraform.io/providers/splunk-terraform/signalfx/latest/docs/resources/event_feed_chart suggests you can use `viz_options` in a `signalfx_event_feed_chart` resource but when you try to, terraform throws an error `Error: Unsupported block type`.

**Comment by atoulme** [comment]
Closing this issue as unplanned. If this issue is still relevant, please reopen the issue.
