### ISSUE TITLE
signalfx_detector AwsEventBridge Notification Support

### ISSUE THREAD

**Issue by MAmba1-nike** [splunk-terraform/terraform-provider-signalfx#297]
Error: Invalid notification type "AmazonEventBridge"

When I try to create signalfx_detector using terraform and with AwsEventBridge Notification terraform plan failing with above listed error

**Comment by gowthamgv2510g** [comment]
Hello, facing same here, any update on the options for adding notifications to configuring Amazon Event Bridge. Is there any options for this usecase?
![image](https://user-images.githubusercontent.com/58732689/130939752-9caedc90-1638-436a-8cbd-41ac145ee530.png)

**Comment by gbloquel** [comment]
Currently, it seems that is not implemented.

see https://github.com/splunk-terraform/terraform-provider-signalfx/blob/v6.8.1/signalfx/notifications.go#L12-L24
There is none `AwsEventBridgeType`.
