### ISSUE TITLE
Error: Failed to validate installed provider

### ISSUE THREAD

**Issue by Keerthana2026** [splunk-terraform/terraform-provider-signalfx#299]
Error: Failed to validate installed provider

Validating provider splunk-terraform/signalfx v6.7.3 failed: provider binary
not found: could not find executable file starting with
terraform-provider-signalfx

running on Windows 10 and Terraform v0.13.2

**Comment by akonarska** [comment]
This regards quite an old version, closing. Please open a new issue if the problem is still there for the newest version.
