### ISSUE TITLE
Cannot create multiple notifications for detector

### ISSUE THREAD

**Issue by gpetrousov** [splunk-terraform/terraform-provider-signalfx#30]
I'm trying to create a detector which will be able to notify on 2 slack channels or 1 slack channel and OpsGenie. However, no matter the combinations I make, the code only picks up the first policy and truncates the rest.

Example:

```
  rule {
    description = "opsgenie and slack"
    severity = "Warning"
    detect_label = "PRD_RDS_FreeStorage_6GB"
    notifications = ["Opsgenie,sometoken,Foo,ABC123,Team,Slack,sometoken,#channel1"]
  }
  rule {
    description = "double slack"
    severity = "Critical"
    detect_label = "PRD_RDS_FreeStorage_5GB"
    notifications = ["Slack,sometoken,#channel1,Slack,sometoken,#channel2"]
  }
```

The `payload` variable looks like:

```
    {opsgenie and slack PRD_RDS_FreeStorage_6GB false [
        map[credentialId:sometoken responderId:ABC123 responderName:Foo responderType:Team type:Opsgenie]]    Warning }

{double slack PRD_RDS_FreeStorage_5GB false [
        map[channel:#channel1 credentialId:sometoken type:Slack]]    Critical }

```

**Comment by cory-signalfx** [comment]
Eep! Lemme dig in to that…

**Comment by cory-signalfx** [comment]
Oh, i see it. You need to separate them out like so:
```
notifications = ["Opsgenie,sometoken,Foo,ABC123,Team", "Slack,sometoken,#channel1"]
```
and
```
notifications = ["Slack,sometoken,#channel1", "Slack,sometoken,#channel2"]
```

That should fix you up.

**Comment by gpetrousov** [comment]
@cory-signalfx Heey that works! That `.split()` is happening on the commas but I was not taking the quotes into account 😅 . Thanks a lot!

Please mark this as solved

**Comment by cory-signalfx** [comment]
Great! Will do, but first I'm going to add some docs so future users have a better chance of catching this. Thanks for flagging!
