### ISSUE TITLE
aws integration creation should implement backoff retry

### ISSUE THREAD

**Issue by xp-1000** [splunk-terraform/terraform-provider-signalfx#308]
Hello,

the aws integration resource obviously requires an aws role with right applied policy to be use during its creation (and validation).

automating all of this process leads to permission denied error because if you create the role and its policy with terraform so it will try to create the integration before the policy is really applied.

the right solution to address this issue is to implement a backoff retry and properly handle the permission denied error into the signalfx provider.

this what official aws provider does for lambda (which also depends on role/policy) : https://github.com/hashicorp/terraform-provider-aws/pull/3116/files and this is, sadly, the behavior expected by AWS as described here https://github.com/hashicorp/terraform-provider-aws/blob/v3.47.0/docs/contributing/retries-and-waiters.md#iam-error-retries.

for more information check the related PR: https://github.com/claranet/terraform-signalfx-integrations/pull/35#issuecomment-872891471

**Comment by atoulme** [comment]
Closing this issue as unplanned. If this issue is still relevant, please reopen the issue.
