### ISSUE TITLE
Dashboard variables deployed in reversed alpha order

### ISSUE THREAD

**Issue by axeljonson** [splunk-terraform/terraform-provider-signalfx#320]
Deploying dashboards with '**variables**' places dashboard overrides in some sort of reverse alphabetical order; but in some cases randomly.

Modifying the alias value shows the following output. In this case the results was not even alphabetical.
![image](https://user-images.githubusercontent.com/34500543/136478321-4a7a8c99-0bf5-4215-b4de-f1e2116b6b49.png)

I have specifically called out each variable as well as used a **dynamic "variable" {}**. 
I have also had use cases using both a **dynamic "variable {}** and individual **variables** in the same dashboard.
The issue is I need them placed in a specific order per requirements. 

This should to be predictable and controllable.

**Comment by atoulme** [comment]
Closing this issue as unplanned. If this issue is still relevant, please reopen the issue.
