### ISSUE TITLE
AWS Account integration -Admin Token issue

### ISSUE THREAD

**Issue by duranhelvaci** [splunk-terraform/terraform-provider-signalfx#322]
Error: Unexpected status code: 403: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 403 Forbidden</title>
</head>
<body><h2>HTTP ERROR 403 Forbidden</h2>
<table>
<tr><th>URI:</th><td>/v2/integration</td></tr>
<tr><th>STATUS:</th><td>403</td></tr>
<tr><th>MESSAGE:</th><td>Forbidden</td></tr>
<tr><th>SERVLET:</th><td>org.glassfish.jersey.servlet.ServletContainer-4531f70f</td></tr>
</table>

</body>
</html>

Please verify you are using an admin token when working with integrations

  on ../module/signalfx.tf line 15, in resource "signalfx_aws_external_integration" "aws_myteam_external":
  15: resource "signalfx_aws_external_integration" "aws_myteam_external" {

**Comment by bgola-signalfx** [comment]
You need to use User API session token when working with integrations.

https://docs.splunk.com/observability/admin/authentication-tokens/api-access-tokens.html#admin-api-access-tokens
