### ISSUE TITLE
Is there a way to create table charts?

### ISSUE THREAD

**Issue by h-azycrazy** [splunk-terraform/terraform-provider-signalfx#323]
In all the documentations I couldn't find a way to create tables in signalfx using terraform. The closest possible way is creating a list. Is there a way to create table charts from terraform?

**Comment by lsglick** [comment]
@h-azycrazy did you ever figure this out?

**Comment by dbottini** [comment]
Jumping on this boat as well - table charts are awesome, and I'd like to be able to use them in Terraform too.

**Comment by atoulme** [comment]
Please refer to https://registry.terraform.io/providers/splunk-terraform/signalfx/latest/docs/resources/table_chart for help. Closing as inactive - please open a support request for any followup. Thanks!
