### ISSUE TITLE
Random Client.Timeout Errors During State Refreshes

### ISSUE THREAD

**Issue by sethfduke** [splunk-terraform/terraform-provider-signalfx#324]
Have many CI/CD workflows hosted on GitHub that all experience the same sporadic timeouts when attempting to refresh the state of detectors, resulting in a net/http: request canceled Client.Timeout exceeded error.

`Error: Get "https://api.us1.signalfx.com/v2/detector/XXXXXXXXXXX": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

This issue has been ongoing, occurs sporadically and on random detectors, and forces constant re-runs of deployment workflows, often requiring several re-tries before finally succeeding.

It would be very helpful if the provider included some option to specify retries when reaching out the the SignalFx API server.

**Comment by rauny-brandao** [comment]
We are facing the same issue. Is there anyone looking into this?

Terraform version: `1.3.7`
SignalFx provider version: `6.20.0`

**Error**

```
Error: Get "https://api.eu0.signalfx.com/v2/dashboard/XXXXX": 
net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by rauny-brandao** [comment]
This error is still going on.

Terraform version: `1.5.2`
SignalFx provider version: `8.0.0`

Error:

```
Error: Get "https://api.eu0.signalfx.com/v2/chart/XXXXX": 
context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by tiedotguy** [comment]
There is a bug with the retry logic in file https://github.com/splunk-terraform/terraform-provider-signalfx/blob/543b1e93719a7ac318ac186e6475192c00df7207/signalfx/provider.go:

- lines 174-182 creates the logging `http.RoundTripper`
- lines 196-199 creates a retryable client with an inner client of `cleanhttp.DefaultPooledClient()`, which defines its own `http.Transport`
- lines 200-201 create a standard `*http.Client` from the retry client, which is a `*http.Client` that consumes the retry clients transport
- line 202 then **throws away the retry clients transport, and replaces it with the logging `http.Transport`**

As a result, we have no retry logic at all, only logging.

Additionally, there is also no actual timeout except for the entire `timeoutSeconds`.  If the backend does not respond in that interval, then the call will fail (if it responds with a 500 or whatever, it will retry however)

I **believe** the following change is sufficient, although it needs some extra glue logic to define/default `bikeshedTimeout`:

```
	retryClient := retryablehttp.NewClient()
	retryClient.HTTPClient.Transport = netTransport
	retryClient.HTTPClient.Timeout = time.Second * time.Duration(int64(bikeshedTimeout))
...
	//standardClient.Transport = netTransport // delete this line
```

This will make the http client on the inside of the retry client have a timeout, and use the the logging transport.  This will flow through to the standardClient using the correct transport, with the correct global and per-request timeouts.

**Comment by dloucasfx** [comment]
@tiedotguy Thanks for the details
Feel free to review the PR.
Note: we use the `DefaultRetryPolicy` in `go-retryablehttp` , ie: it will not retry on context timeout https://github.com/hashicorp/go-retryablehttp/blob/v0.7.4/client.go#L447

**Comment by tiedotguy** [comment]
Hi @dloucasfx, the fix makes it so that only a non-success response (ie, 5xx, 4xx) will result in retries.  If the backend times out (which is the origin of this issue), then it won't retry.

The underlying `retryClient` still needs its own timeout configured (with exact variable to be bikeshed still):

```
	retryClient.HTTPClient.Timeout = time.Second * time.Duration(int64(bikeshedTimeout))
```

**Comment by dloucasfx** [comment]
@tiedotguy 
Yes, that makes sense.
I asked the original author @dscott-splunk to address this, please check this PR https://github.com/splunk-terraform/terraform-provider-signalfx/pull/468
