### ISSUE TITLE
darwin_arm64 provider version

### ISSUE THREAD

**Issue by hlepesant** [splunk-terraform/terraform-provider-signalfx#325]
Hi,

Can you build and release a darwin_arm64 version of the SignalFX provider ?

I'm using terraform darwin_arm64 and I can't  use this provider
A terraform init report this error
```
Error: Incompatible provider version  
Provider registry.terraform.io/splunk-terraform/signalfx v6.7.8 does not have a package available for your current platform, darwin_arm64.  
Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.  
```

**Comment by hlepesant** [comment]
I've build the provider on my side (MacBook Pro M1 / macos BigSure 11.6).
And it works as expected.
I've installed it in 
```
~/.terraform.d/plugins/github/splunk-terraform/signalfx/6.7.8/darwin_arm64/terraform-provider-signalfx
```

regards

**Comment by vranystepan** [comment]
I'd say we just need to remove this... 
https://github.com/splunk-terraform/terraform-provider-signalfx/blob/main/.goreleaser.yml#L27

**Comment by bgola-signalfx** [comment]
Done. Thanks for your contribution!
https://github.com/splunk-terraform/terraform-provider-signalfx/releases/tag/v6.10.0
