### ISSUE TITLE
The "Add Conditions" to data links to dashboards is not available.

### ISSUE THREAD

**Issue by axeljonson** [splunk-terraform/terraform-provider-signalfx#326]
In the SFx UI I can create a data link to another dashboard and can "Add Conditions" to when that data link will be visible. However the SFx Provider does not support this feature. Can this be added?
This is described (vaguely) in the [SFx Navigation page](https://docs.splunk.com/Observability/data-visualization/chart-and-dashboard-features/navigate-with-data-links.html#navigate-with-data-links).
![image](https://user-images.githubusercontent.com/34500543/139911828-309b6870-9dbf-4706-a90e-bb6ed503a4a3.png)

**Comment by atoulme** [comment]
Closing this issue as unplanned. If this issue is still relevant, please reopen the issue.
