### ISSUE TITLE
 Add ability to set up Azure integration via Terraform

### ISSUE THREAD

**Issue by a-staebler** [splunk-terraform/terraform-provider-signalfx#33]
Would be useful to have this for Azure too.

**Comment by cory-signalfx** [comment]
Excellent! I'm currently working on #32 so this is adjacent and relevant!

**Comment by cory-signalfx** [comment]
Hey @a-staebler, this is done. I'll do a release later this week.

**Comment by a-staebler** [comment]
Awesome! 🎇
