### ISSUE TITLE
SFx Provider does not support dashboard permission inheritance

### ISSUE THREAD

**Issue by axeljonson** [splunk-terraform/terraform-provider-signalfx#336]
On Dec 2, 2021, SFx released a new feature that allows the dashboard to inherit permissions from the associated dashboard group. The SFx provider does not support the different dashboard group settings. Providing no custom permissions for any of the dashboards (i.e. no 'authorized_writer_teams' or 'authorized_writer_user' configuration) and providing the following the following permissions for the dashboard group:
`authorized_writer_teams = ["team-id"]`

Will set set the permissions for the dashboard group to read/write by everyone.
This needs to be fixed as all of our deploys are now broke!

**Comment by luke-sterkowicz** [comment]
Added in [v6.11.0](https://github.com/splunk-terraform/terraform-provider-signalfx/releases/tag/v6.11.0)
