### ISSUE TITLE
`high_watermark` and `low_watermark` are always being updated during `apply` if their values are not set

### ISSUE THREAD

**Issue by justinskariah** [splunk-terraform/terraform-provider-signalfx#35]
If `high_watermark` and `low_watermark` are not set in `signalfx_time_chart` -> `axis_left`,
default handling for `high_watermark` and `low_watermark` causes it to be set for every `apply`.

Steps to reproduce:
* Create a `signalfx_time_chart` resource with the following `axis_left`
```
  axis_left {
    label = "%"
    min_value = 0
    max_value = 110
  }
```
* Run `terraform apply` to create the new chart
* Run `terraform apply` again
* You would see the following changes to `apply`, even though you have not made any changes to `axis_left`

```
      - axis_left {
          - high_watermark = 179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 -> null
          - label          = "%" -> null
          - low_watermark  = 179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 -> null
          - max_value      = 110 -> null
          - min_value      = 0 -> null
        }
      + axis_left {
          + high_watermark = 340282346638528860000000000000000000000
          + label          = "%"
          + low_watermark  = -340282346638528860000000000000000000000
          + max_value      = 110
          + min_value      = 0
        }
```

Expected behaviour
* `terraform apply` should return no changes to apply

Terraform version:
```
Terraform v0.12.5
+ provider.signalfx v4.3.0
```

**Comment by cory-signalfx** [comment]
Hey @justinskariah! First, thanks so much for the minimal test case!

Next, can you confirm that you are using the latest version of the provider? I believe that this was fixed in #24. Doing local tests on your example shows a clean `terraform apply` after the first one finishes.

**Comment by justinskariah** [comment]
Yes, I am on the latest version. Sorry, I should have added that to the bug details.
```
Terraform v0.12.5
+ provider.signalfx v4.3.0
```
I think this was introduced with [these](https://github.com/terraform-providers/terraform-provider-signalfx/pull/24#issuecomment-514221587) changes

**Comment by cory-signalfx** [comment]
Ok, I can repro this now. I had a sneaky (old) provider installed in the directory I tried to test this minimal case in. On it!

**Comment by justinskariah** [comment]
Awesome, thanks @cory-signalfx for fixing it.
