### ISSUE TITLE
Adding properties using MetricMetadata

### ISSUE THREAD

**Issue by FalconerTC** [splunk-terraform/terraform-provider-signalfx#352]
Hello. Is there a resource that allows you to add properties to a dimension, as you can do in the UI via the MetricMetdata?
<img width="1743" alt="image" src="https://user-images.githubusercontent.com/2731258/156615656-2fb33cb1-8ab5-4a4b-806f-dfc630279d66.png">

It looks like this is a call to the `v1/dimension/*` endpoint.

Thank you!

**Comment by atoulme** [comment]
This is not currently supported, from a cursory review.

I have opened a Splunk idea to follow up: https://ideas.splunk.com/ideas/SFXIMMID-I-625

Please feel free to upvote and comment on it to follow up.
