### ISSUE TITLE
signal_aws_integration regions does not handle null values

### ISSUE THREAD

**Issue by anelson-splunk** [splunk-terraform/terraform-provider-signalfx#364]
Documentation indicates that the `regions` attribute is completely optional when using this provider. However, if a null value is passed in, this provider does not account for it and actually sets the value as null in SignalFx which causes issues for the end user when they look at the AWS Integration in the SignalFx UI.

The provider should set a default value so if users provide bad input then it sets the value to an empty list so that end users don't see errors in the web ui.
https://github.com/splunk-terraform/terraform-provider-signalfx/blob/main/signalfx/resource_signalfx_aws_integration.go#L146-L147

![image](https://user-images.githubusercontent.com/87780424/159987229-156710a0-326a-4321-b788-5e649a796a4e.png)

**Comment by anelson-splunk** [comment]
Further investigation points to an alternate root cause to the problem. Terraform code does not pass in a value for `named_token` and the provider doesn't use the value of "Default" which is what the API will default to, but instead passed null.
https://github.com/splunk-terraform/terraform-provider-signalfx/blob/main/signalfx/resource_signalfx_aws_integration.go#L205-L209
https://dev.splunk.com/observability/reference/api/integrations/latest#endpoint-create-integration

**Comment by ewanlyall** [comment]
we are also experiencing this behaviour on `v6.11.1`.

Similarly, setting `regions = []` is also passed to SignalFx as `null`.

I can't see any evidence that the provider has changed behaviour in this respect, so I'm assuming that the API has changed at some point. The original behaviour was that passing an empty list of regions would enable **all** regions in the SFx integration.

Using this as a workaround for now

```hcl
data "aws_regions" "this" {}

resource "signalfx_aws_integration" "this" {
  regions = data.aws_regions.this.names
  .
  .
  .
}
```

**Comment by penglerts** [comment]
@anelson-splunk @ewanlyall in the long term we will move from supporting all regions options, as it can lead to unexpected cost increate when AWS add new region and it will be sync automatically. We will move toward explicit model when you need to provide list of all regions. However for you is it something which was important?

Related issues above, now we treat null same as empty list == all regions will be sync, and you should see that in UI

**Comment by ewanlyall** [comment]
@penglerts thanks for the update. No, I don't have a requirement to automatically sync new regions. And your reasons for not doing so make perfect sense.

I guess I was just caught out by the mismatch between the documented provider behaviour and the underlying API.

**Comment by penglerts** [comment]
@anelson-splunk I tested it with `namedToken` and it works as expected. If you still have similar issue please reopen the ticket
