### ISSUE TITLE
plugin crash 

### ISSUE THREAD

**Issue by mnegron1** [splunk-terraform/terraform-provider-signalfx#374]
Error: Plugin did not respond
Stack trace from the terraform-provider-signalfx_v6.13.0 plugin:

panic: interface conversion: interface {} is *schema.Set, not []interface {}

goroutine 52 [running]:
github.com/splunk-terraform/terraform-provider-signalfx/signalfx.getPayloadDetector(0xc0000ea960?)
        github.com/splunk-terraform/terraform-provider-signalfx/signalfx/resource_signalfx_detector.go:387 +0xcb5
github.com/splunk-terraform/terraform-provider-signalfx/signalfx.detectorCreate(0x188e380?, {0x1830420?, 0xc0000ad600?})
        github.com/splunk-terraform/terraform-provider-signalfx/signalfx/resource_signalfx_detector.go:459 +0x4c
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000205a70, 0xc0002d6aa0, 0xc0000ea960, {0x1830420, 0xc0000ad600})
        github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/resource.go:310 +0x438
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0000ae080, 0xc000265960, 0x198afe7?, 0xf?)
        github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/provider.go:294 +0x70
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000a6450, {0xc00047c3f0?, 0x10b1826?}, 0xc00047c3f0)
        github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/helper/plugin/grpc_provider.go:885 +0x7c5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x19555a0?, 0xc0000a6450}, {0x1b1cd28, 0xc0002bee70}, 0xc000696240, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00046a480, {0x1b1f9e0, 0xc00046a600}, 0xc00065c000, 0xc0007963c0, 0x20187a0, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1024 +0xd1e
google.golang.org/grpc.(*Server).handleStream(0xc00046a480, {0x1b1f9e0, 0xc00046a600}, 0xc00065c000, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1313 +0xa05
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.27.1/server.go:722 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.27.1/server.go:720 +0xea

Error: The terraform-provider-signalfx_v6.13.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by bohdanborovskyi-ma** [comment]
@mnegron1  Apparently, this bug was solved in [v6.13.1](https://github.com/splunk-terraform/terraform-provider-signalfx/releases/tag/v6.13.1) provider release. 
Please upgrade the provider and test if crash remains re-producible
