### ISSUE TITLE
Plugin Crashed

### ISSUE THREAD

**Issue by apoorva88** [splunk-terraform/terraform-provider-signalfx#375]
Error: Request cancelled
│ 
│   with module.signalfx-detectors-integration-aws-sqs["efgwrcptrgtadptr-intake-dlq-prod"].signalfx_detector.age_of_oldest_message,
│   on .terraform_prod/modules/signalfx-detectors-integration-aws-sqs/modules/integration_aws-sqs/detectors-sqs.tf line 69, in resource "signalfx_detector" "age_of_oldest_message":
│   69: resource "signalfx_detector" "age_of_oldest_message" {
│ 
│ The plugin.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵

Stack trace from the terraform-provider-signalfx_v6.13.0 plugin:

panic: interface conversion: interface {} is *schema.Set, not []interface {}

goroutine 43 [running]:
github.com/splunk-terraform/terraform-provider-signalfx/signalfx.getPayloadDetector(0xc00004c800?)
	github.com/splunk-terraform/terraform-provider-signalfx/signalfx/resource_signalfx_detector.go:387 +0xcb5
github.com/splunk-terraform/terraform-provider-signalfx/signalfx.detectorCreate(0xc8f940?, {0xc32160?, 0xc000122900?})
	github.com/splunk-terraform/terraform-provider-signalfx/signalfx/resource_signalfx_detector.go:459 +0x4c
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00012d0e0, 0xc0004a8730, 0xc00004c800, {0xc32160, 0xc000122900})
	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/resource.go:310 +0x438
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00012a080, 0xc0001ab960, 0xd8c122?, 0xf?)
	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/provider.go:294 +0x70
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00011c0d0, {0xc000228380?, 0x4b63e6?}, 0xc000228380)
	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/helper/plugin/grpc_provider.go:885 +0x7c5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd55fa0?, 0xc00011c0d0}, {0xf1e3c8, 0xc0004bcff0}, 0xc00050c1e0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000452480, {0xf21000, 0xc0001e4000}, 0xc000126600, 0xc000584330, 0x1416700, 0x0)
	google.golang.org/grpc@v1.27.1/server.go:1024 +0xd1e
google.golang.org/grpc.(*Server).handleStream(0xc000452480, {0xf21000, 0xc0001e4000}, 0xc000126600, 0x0)
	google.golang.org/grpc@v1.27.1/server.go:1313 +0xa05
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.27.1/server.go:722 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.27.1/server.go:720 +0xea

Error: The terraform-provider-signalfx_v6.13.0 plugin crashed!

**Comment by bohdanborovskyi-ma** [comment]
@apoorva88 Apparently, this bug was solved in [v6.13.1](https://github.com/splunk-terraform/terraform-provider-signalfx/releases/tag/v6.13.1) provider release. 
Please upgrade the provider and test if crash remains re-producible
