### ISSUE TITLE
Plugin didn't Respond 

### ISSUE THREAD

**Issue by ShubhangiUpadhyay** [splunk-terraform/terraform-provider-signalfx#381]
**Error: Plugin did not respond
│ 
│   with splunk_inputs_monitor.monitor,
│   on main.tf line 15, in resource "splunk_inputs_monitor" "monitor":
│   15: resource "splunk_inputs_monitor" "monitor" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-splunk_v1.4.13 plugin:

panic: runtime error: index out of range [0] with length 0**

goroutine 39 [running]:
github.com/splunk/terraform-provider-splunk/splunk.getInputsMonitorConfigByName({0x140000361b0, 0x24}, 0x14000726000)
        github.com/splunk/terraform-provider-splunk/splunk/resource_splunk_inputs_monitor.go:324 +0x2c0
github.com/splunk/terraform-provider-splunk/splunk.inputsMonitorRead(0x14000716620, {0x103262fe0, 0x140005cc130})
        github.com/splunk/terraform-provider-splunk/splunk/resource_splunk_inputs_monitor.go:159 +0x174
github.com/splunk/terraform-provider-splunk/splunk.inputsMonitorCreate(0x14000716620, {0x103262fe0, 0x140005cc130})
        github.com/splunk/terraform-provider-splunk/splunk/resource_splunk_inputs_monitor.go:146 +0x314
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0x14000456d80, 0x1400070e370, 0x140001449c0, {0x103262fe0, 0x140005cc130})
        github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/resource.go:310 +0x528
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0x140001ba000, 0x140000dba10, 0x1400070e370, 0x140001449c0)
        github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/provider.go:294 +0x88
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0x14000120068, {0x1033c1d50, 0x1400070c1b0}, 0x14000716000)
        github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/helper/plugin/grpc_provider.go:885 +0x8cc
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x103377380, 0x14000120068}, {0x1033c1d50, 0x1400070c1b0}, 0x140000e0060, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x140001d6480, {0x1033cd080, 0x14000434000}, 0x1400009c200, 0x14000099440, 0x1038ce760, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1024 +0xcdc
google.golang.org/grpc.(*Server).handleStream(0x140001d6480, {0x1033cd080, 0x14000434000}, 0x1400009c200, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1313 +0xa94
google.golang.org/grpc.(*Server).serveStreams.func1.1(0x1400020c1e0, 0x140001d6480, {0x1033cd080, 0x14000434000}, 0x1400009c200)
        google.golang.org/grpc@v1.27.1/server.go:722 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.27.1/server.go:720 +0x8c

**Error: The terraform-provider-splunk_v1.4.13 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.**

**Comment by navtej-splunk** [comment]
Hi @ShubhangiUpadhyay ,
Thanks a lot for reporting this issue. I am PM and would be looking into this issue.
Can you help us with additional details - about specific module configuration and steps to be taken that might lead to this issue?

Looking forward to hearing from you.
Best,
Navtej

**Comment by akonarska** [comment]
Hey @ShubhangiUpadhyay - you mixed the providers. Splunk Terraform Provider can be found here - if the problem is still there please report it here https://github.com/splunk/terraform-provider-splunk
