### ISSUE TITLE
Feature Request: Add RUM

### ISSUE THREAD

**Issue by muzeke** [splunk-terraform/terraform-provider-signalfx#390]
Hi, 

Just wondering if we have any future plans of adding RUM to the terraform provider? It would be helpful to keep it in IaC.

**Comment by leij-splunk** [comment]
I think you can use `auth_scopes` to configure auth token scopes. 
`auth_scopes` supports `RUM`.

**Comment by atoulme** [comment]
Closing as complete. Please open a support request to receive further help.
