### ISSUE TITLE
Feature request: Getting rid of the need for session tokens

### ISSUE THREAD

**Issue by maltefiala** [splunk-terraform/terraform-provider-signalfx#399]
**Current Scenario**
Currently, several operations are only doable using your personal session token, aquireable by hand on the personal user's profile page.

See also https://dev.splunk.com/observability/docs/administration/authtokens/#Operations-that-require-a-session-token-for-an-administrator

**Target scenario**
Personal session tokens are no longer needed for automated tasks. Instead, organization tokens with Admin permissions can be created:
![Create access token](https://user-images.githubusercontent.com/526184/203512521-c05943f6-acfe-4630-ae1d-a37253132ef3.png)

**Comment by navtej-splunk** [comment]
Hi @maltefiala,
This is Navtej, a PM on this issue and I am enquiring more details on this.
Thank you for the feature request regarding session tokens. We understand the current need for personal session tokens for certain operations. In the target scenario, we aim to remove the requirement for personal session tokens by introducing organization tokens with Admin permissions. This will simplify automated tasks. We appreciate your suggestion and will consider it for future improvements. 
If you have any additional details or suggestions, please let us know.

**Comment by maltefiala** [comment]
Hi @navtej-splunk , sounds great, thanks for your reply!

**Comment by MovieStoreGuy** [comment]
Hey @maltefiala , 

This should be solved by the most recent updates to the [tokens api](https://dev.splunk.com/observability/reference/api/org_tokens/latest). 

There are some cases that you may need one off usage of your personal token, but they should be rare. 

I am going to close this off and if you have any follow ups, I do suggest reaching out to support or your account team :)
