### ISSUE TITLE
Exclude action needed for  `custom_namespace_sync_rule` of the `signalfx_aws_integration` terraform resource.

### ISSUE THREAD

**Issue by dwalczakfx** [splunk-terraform/terraform-provider-signalfx#408]
We need to correct the documentation - 

Using Exclude action without an Include filter which is redundant results in failed integration /not tracking default action state.
The default action exclude, expects an include filter and vice versa.

Please add it to the docs.

**Comment by navtej-splunk** [comment]
Hi @dwalczakfx,
Thanks a lot for reaching out to us. I am a PM and would be working on this issue. Can you help me with more details on the specific behavior or expected outcome when using the Exclude action without an include filter? This will us in ensuring accurate and updated documentation. 
Really appreciate your feedback and looking forward to your response.

Best,
Navtej
