### ISSUE TITLE
Missing Service : microsoft.dbforpostgresql/flexibleservers

### ISSUE THREAD

**Issue by Poil** [splunk-terraform/terraform-provider-signalfx#426]
Hi,

This is supported by the portal but not the provider (data azure_services)

Regards

**Comment by BzSpi** [comment]
Waiting for https://github.com/signalfx/signalfx-go/pull/194

**Comment by navtej-splunk** [comment]
@Poil,
Thank you for reaching out on GitHub. We appreciate your feedback and would like to gather more information about the issue you encountered. This will help us investigate and address it effectively. Rest assured, we take user-reported issues seriously and will prioritize resolving it. We will keep you updated on the progress. 
Additionally, we have noted your request to add support for Azure services like PostgreSQL flexible, Recovery Vault, and Backup Vault. Thank you for your patience, and if you have any further details to share, please let us know.

**Comment by akonarska** [comment]
@Poil @BzSpi We just released v7.0.0 with support for that https://github.com/splunk-terraform/terraform-provider-signalfx/releases/tag/v7.0.0
