### ISSUE TITLE
signalfx_org_token resource trying  to create new token in each Terraform plan

### ISSUE THREAD

**Issue by benzch** [splunk-terraform/terraform-provider-signalfx#435]
Hi, 
I am using provider version 6.24 and terraform 1.5.0. 
At first apply token is created successfully and saved to state, 
when running Terraform again it will detect change outside of Terraform (that didn't happen) and  try recreate the resource. 

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply" which may have affected this plan:
  # signalfx_org_token.ingest_token has been deleted
  - resource "signalfx_org_token" "ingest_token" {
        id            = "ingest token"
        name          = "ingest token"
      - secret        = (sensitive value) -> null
        # (3 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions
to undo or respond to these changes.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # signalfx_org_token.ingest_token will be created
  + resource "signalfx_org_token" "ingest_token" {
      + auth_scopes   = [
          + "INGEST",
        ]
      + disabled      = false
      + id            = (known after apply)
      + name          = "ingest token"
      + secret        = (sensitive value)
    }
```

**Comment by benkeith-splunk** [comment]
@benzch I would use the [lifecycle ignore_changes](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) option on this resource as a workaround until we can figure this out. I'm not sure if it is feasible to detect regenerated token values or not so we probably need to somehow mark the secret field as ignored but I'll have to look into how to do that but this workaround should squash it for now.

**Comment by benzch** [comment]
Life cycle rule didn't work for me, terraform trying to create "new" resource, same behaviour  as if the resource is missing from the tfstate.

**Comment by asaphe** [comment]
Hi @benkeith-splunk we are also seeing this behavior and there's also no option to import existing tokens.
