### ISSUE TITLE
Org Tokens - Missing Limit Configurations

### ISSUE THREAD

**Issue by anelson-splunk** [splunk-terraform/terraform-provider-signalfx#462]
The following items are configureable through the API on org tokens but are not available in the terraform provider;
- limits.eventSearchesPerMinute
- limits.jobsPerMinuteLimit
- limits.mtsmLimit

https://dev.splunk.com/observability/reference/api/org_tokens/latest#endpoint-update-single-token

For an organization that managed all of their Org tokens with terraform, it's very inconvenient that these items are not configurable through the terraform provider. In order to set these limits it must be done manually through the browser which means configurations in TF don't exactly match.

**Comment by atoulme** [comment]
Thank you for your report!
I have opened the Splunk idea https://ideas.splunk.com/ideas/SFXIMMID-I-624 to follow up. Please feel free to upvote and comment.
