### ISSUE TITLE
Implement muting rule reccurence

### ISSUE THREAD

**Issue by BzSpi** [splunk-terraform/terraform-provider-signalfx#469]
Hello,

muting rule recurrence is now available in API (and thank you for that !).
It should be implemented in `signalfx_alert_muting_rule` resource.

edit: documentation: https://dev.splunk.com/observability/reference/api/incidents/latest#endpoint-create-single-muting-rule

Thanks

**Comment by atoulme** [comment]
Thank you for your report! I have filed your request as a Splunk idea here: https://ideas.splunk.com/ideas/SFXIMMID-I-627

Please feel free to upvote or comment on it to follow up.
