### ISSUE TITLE
[Feature Request] Add support for universal tags for Opsgenie

### ISSUE THREAD

**Issue by gjethwani** [splunk-terraform/terraform-provider-signalfx#471]
Hi,

We use Terraform to manage our detectors which notify us using Opsgenie. For routing purposes, we would like to add universal tags to all detectors. Something that designates what service this alert is coming from. Can we add support for these tags in the `opsgenie_notification` string? 

I'm happy to contribute this change, but can you confirm what i would have to add to this object to support tags being added to the Opsgenie notification?
```
case OpsgenieNotificationType:
	n = &notification.OpsgenieNotification{
		Type:          vars[0],
		CredentialId:  vars[1],
		ResponderName: vars[2],
		ResponderId:   vars[3],
		ResponderType: vars[4],
	}
```

**Comment by MovieStoreGuy** [comment]
Hey @gjethwani,

This is something that is via the detector itself rather than with the integration. The integration should pass through all the dimensions as tags that you can use for routing purposes. 

I suggest reaching out to support or your account team to follow this up.
