### ISSUE TITLE
time_range problem

### ISSUE THREAD

**Issue by doctornkz** [splunk-terraform/terraform-provider-signalfx#55]
Maybe it related with #17. 
We have a terraform config like that:
```
resource "signalfx_time_chart" "sfx-D8XMAaAAAAA" {
  name              = "Total Sent Bytes / Min"
  description       = ""
  plot_type         = "AreaChart"
  stacked           = false
  axes_include_zero = false
  histogram_options {
    color_theme = "red"
  }
  viz_options               = [{ label = "A", value_prefix = "", value_suffix = "" }]
  program_text              = <<EOF
A = data('SentMessageSize', filter=filter('namespace', 'AWS/SQS') and filter('stat', 'sum')).scale(60).sum().publish(label='A')
EOF
  disable_sampling          = false
  minimum_resolution        = 0
  unit_prefix               = "Metric"
  max_delay                 = 0
  color_by                  = "Dimension"
  on_chart_legend_dimension = ""
}
```
I want to add custom `time_range` to chart as described in documentation here:
https://www.terraform.io/docs/providers/signalfx/r/time_chart.html

But after plan stage I receive error:
```
Error: signalfx_time_chart.sfx-D8XMAaAAAAA: time_range: cannot parse '' as int: strconv.ParseInt: parsing "-2h": invalid syntax
```
Maybe I need to use int for -2h, but documentation's examples tells opposite:
```
time_range = "-15m"
```

**Comment by doctornkz** [comment]
Need to say dashboard time_range works fine. Only charts broken.

**Comment by cory-signalfx** [comment]
Dang. The docs are wrong. This should be specified as the number of seconds. Instead of `-1h` it's '3600`.

I can adjust the docs to fix this, sorry you hit it!

Does that sound right? Wanna verify? (Yes, dashboards use a different format. Ugh)

**Comment by doctornkz** [comment]
It works, Cory! Thank you so much!
