### ISSUE TITLE
Terraform state is always updating on_chart_legend_dimension

### ISSUE THREAD

**Issue by noliva** [splunk-terraform/terraform-provider-signalfx#57]
Basically, every time we run Terraform, it tries to update the same dashboards even though they already exist and are aligned because it's trying to modify a field called `on_chart_legend_dimension`

```
resource "signalfx_time_chart" "status_codes" {
        axes_include_zero         = false
        axes_precision            = 3
        color_by                  = "Dimension"
        disable_sampling          = false
        id                        = "ourID"
        name                      = "2XX/4XX/5XX"
      ~ on_chart_legend_dimension = "sf_metric" -> "plot_label"
        plot_type                 = "LineChart" 
```

It would be nice if it only tried to update when there was a real update.

**Comment by cory-signalfx** [comment]
Oh dear! Sorry you hit this and thanks for flagging, I'll investigate now so we can get it in for the release I planned tomorrow.

**Comment by noliva** [comment]
Awesome, thank you very much for your help!

**Comment by cory-signalfx** [comment]
Hey @noliva, I'll go ahead and do a release of the provider now as I'm gonna be busy tomorrow and unlikely to make any other changes. Thanks again for reporting!

**Comment by noliva** [comment]
Wow, that was super efficient, thank you so much for solving that issue so quickly!

**Comment by cory-signalfx** [comment]
No problem, I can't promise to always be that fast. Today I was free and the fix was pretty easy! :)

**Comment by doctornkz** [comment]
Hi! It's closed, but I am still receiving update status from atlantis (terraform manager):
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

~ signalfx_time_chart.sfx-EEQhYl9AAAA
      on_chart_legend_dimension: "metric" => "sf_originatingMetric"

~ module.base.signalfx_dashboard_group.default-dashboard-group
      teams.#:                   "1" => "0"
      teams.0:                   "Dxs0uliAAh8" => ""
Plan: 0 to add, 2 to change, 0 to destroy.
```
I have this config:
```
resource "signalfx_time_chart" "sfx-EEQhYl9AAAA" {
  name                      = "Catalog - API GW"
  description               = "Catalog Production"
  plot_type                 = "AreaChart"
  stacked                   = true
  axes_include_zero         = false
  viz_options               = [{ color = "blue", display_name = "Latency", label = "A", plot_type = "AreaChart", value_prefix = "", value_suffix = "", value_unit = "Millisecond" }, { axis = "right", color = "green", display_name = "CacheHitCount", label = "E", plot_type = "ColumnChart", value_prefix = "", value_suffix = "" }, { axis = "right", color = "purple", display_name = "CacheMissCount", label = "D", plot_type = "ColumnChart", value_prefix = "", value_suffix = "" }]
  event_options             = []
  program_text              = <<EOF
A = data('Latency', filter=filter('ApiName', 'Catalog-API') and filter('stat', 'upper') and filter('Stage', 'v1') and (not filter('AWSUniqueId', '*central*')), rollup='max', extrapolation='last_value').publish(label='A')
D = data('CacheMissCount', filter=filter('ApiName', 'Catalog-API') and filter('Stage', 'v1') and filter('stat', 'sum') and (not filter('AWSUniqueId', '*central*')), rollup='sum').publish(label='D')
E = data('CacheHitCount', filter=filter('ApiName', 'Catalog-API') and filter('Stage', 'v1') and filter('stat', 'sum') and (not filter('AWSUniqueId', '*central*')), rollup='sum').publish(label='E')

EOF
  disable_sampling          = false
  minimum_resolution        = 0
  unit_prefix               = "Metric"
  max_delay                 = 0
  color_by                  = "Metric"
  on_chart_legend_dimension = "sf_originatingMetric"
  time_range                = 900
```
I pretty sure we are using last terraform provider. May be I forgot something?

**Comment by cory-signalfx** [comment]
Will take a look, @doctornkz! Do you know your provider version?

**Comment by doctornkz** [comment]
Cory, seems I have bug in my config 
```
on_chart_legend_dimension = "sf_originatingMetric" 
```
it doesn't make any sense, right? 
Documentation:

**legend_options_fields** - (Optional) List of property names and enabled flags that should be displayed in the data table for the chart, in the order provided. This option cannot be used with legend_fields_to_hide.
property The name of the property to display. Note the special values of sf_metric which shows the label of the time series publish() and _sf_originatingMetric_ that shows the name of the metric for the time series being displayed.

Maybe I am using wrong attribute. I will check.

**Comment by cory-signalfx** [comment]
The confusion is my fault, the docs are subtly wrong. Patch incoming. For now, you want to use the value `metric` instead of `sf_originatingMetric`.
