### ISSUE TITLE
Unmarshal nil error within v4.6

### ISSUE THREAD

**Issue by MovieStoreGuy** [splunk-terraform/terraform-provider-signalfx#59]
When reapplying an existing terraform state and (I assume) when terraform does the refresh it tries to unmarshal nil and throws an error.

I have a current work around to pin the provider to an older version for the time being.

Terraform v0.12.6
Provider verison: v4.6.0

**Comment by cory-signalfx** [comment]
That's no good! Can you share the crash log or any other information? Unfortunately such a crash could be just about anywhere. :(
