### ISSUE TITLE
EventPublishLabelOptions structure is not supported

### ISSUE THREAD

**Issue by doctornkz** [splunk-terraform/terraform-provider-signalfx#61]
As example, I have a config like this:
```
resource "signalfx_time_chart" "sfx-EBq0cWjAAAA" {
............cut start.............
  viz_options               = [{ display_name = "gitlab.deployment", label = "A", value_prefix = "", value_suffix = "" }, { display_name = "gitlab.deployment", label = "C", value_prefix = "", value_suffix = "" }, { display_name = "gitlab.deployment", label = "D", value_prefix = "", value_suffix = "" }, { display_name = "gitlab.deployment", label = "B" }, { color = "orange", display_name = "gitlab.deployment", label = "F" }]
  program_text              = <<EOF
A = data('gitlab.deployment', filter=filter('application_name', 'carspt') and filter('status', 'succeed'), rollup='sum').publish(label='A')
C = data('gitlab.deployment', filter=filter('application_name', 'autovitro') and filter('status', 'succeed'), rollup='sum').publish(label='C')
D = data('gitlab.deployment', filter=filter('application_name', 'otomotopl') and filter('status', 'succeed'), rollup='sum').publish(label='D')
B = events(eventType='gitlab.deployment', filter=filter('application_name', 'carspt') and filter('status', 'succeed')).publish(label='B')
F = events(eventType='gitlab.deployment', filter=filter('type', 'redeploy') and filter('status', 'succeed')).publish(label='F')
EOF
...........cut end................
}
```
after applying, I receive error:

```
Error: Error applying plan:
1 error(s) occurred:
* signalfx_time_chart.sfx-EBq0cWjAAAA: 1 error(s) occurred:
* signalfx_time_chart.sfx-EBq0cWjAAAA: Unexpected status code: 400: {
  "code" : 400,
  "message" : "Label \"F\" defined in publish options was not found in any publish block in the program text."
}
``` 

I did grep all repo recursively and figured out that terraform provider doesn't process the structure, like `PublishLabelOptions`
Seems that **events** labels are not supported yet, but maybe I am doing smth wrong?

**Comment by cory-signalfx** [comment]
Drat. No, you're doing nothing wrong. I didn't realize this was a different structure. In fact, I started typing a response to this saying it *was* supported then eventually realized I was missing the `Event` prefix. :(

Seems like the fix here is to add an `event_options` which is basically the same thing. Thoughts?

**Comment by cory-signalfx** [comment]
nb that this is also [not documented for chart creation](https://developers.signalfx.com/charts_reference.html#operation/Create%20Single%20Chart)

**Comment by doctornkz** [comment]
Thank you! `event_options` looks like my case, I gonna test that.

**Comment by doctornkz** [comment]
Sorry me, Cory. But I faced with some syntax problem here...
In code we have totally clear proposal for using new structure:
viz_options here : https://github.com/terraform-providers/terraform-provider-signalfx/blob/master/signalfx/resource_signalfx_time_chart.go#L393

event_options here : https://github.com/terraform-providers/terraform-provider-signalfx/blob/master/signalfx/resource_signalfx_time_chart.go#L447

These are two different structures and should be used independently. But this config crashes my terraform with last provider:
```
resource "signalfx_time_chart" "sfx-EBq0cWjAAAA" {
  name              = "Deployment over days"
  description       = "Successful deployments per day"
  plot_type         = "ColumnChart"
  stacked           = true
  axes_include_zero = false
  histogram_options {
    color_theme = "red"
  }
  viz_options               = [{ display_name = "gitlab.deployment", label = "A", value_prefix = "", value_suffix = "" }, { display_name = "gitlab.deployment", label = "C", value_prefix = "", value_suffix = "" }, { display_name = "gitlab.deployment", label = "D", value_prefix = "", value_suffix = "" }]
  event_options             = [{ display_name = "gitlab.deployment", label = "B" }, { color = "orange", display_name = "gitlab.deployment", label = "F" }]
  program_text              = <<EOF
A = data('gitlab.deployment', filter=filter('application_name', 'carspt') and filter('status', 'succeed'), rollup='sum').publish(label='A')
C = data('gitlab.deployment', filter=filter('application_name', 'autovitro') and filter('status', 'succeed'), rollup='sum').publish(label='C')
D = data('gitlab.deployment', filter=filter('application_name', 'otomotopl') and filter('status', 'succeed'), rollup='sum').publish(label='D')
B = events(eventType='gitlab.deployment', filter=filter('application_name', 'carspt') and filter('status', 'succeed')).publish(label='B')
F = events(eventType='gitlab.deployment', filter=filter('type', 'redeploy') and filter('status', 'succeed')).publish(label='F')
EOF
  disable_sampling          = false
  minimum_resolution        = 0
  unit_prefix               = "Metric"
  max_delay                 = 0
  color_by                  = "Dimension"
  on_chart_legend_dimension = "application_name"
  time_range                = 900
}
```
Terraform error: https://gist.github.com/doctornkz/de222e09d59c326c4a354f9e699a5269

I went to documentation and found that `event_options` it's a nested structure of `viz_options`
if it's true, how I should organize the `list` object related with viz_options? 

I am a bit confused here (

**Comment by cory-signalfx** [comment]
I can reproduce the crash, thanks for the xample case. Gonna make a new issue.

**Comment by cory-signalfx** [comment]
Gonna bug hashi for a release, should see it land in a few hours!

**Comment by doctornkz** [comment]
What do you think about split-brain in documentation? It is nested or independent? 
PS. I tested, it's working now and it's independent. Thanks, Cory

**Comment by cory-signalfx** [comment]
It's independent and fixed. Thank you for flagging that. It's one of the downsides of not being able to see those docs until they hit the HashiCorp site. :(
