### ISSUE TITLE
"one step" AWS account integration

### ISSUE THREAD

**Issue by kimor79** [splunk-terraform/terraform-provider-signalfx#72]
Currently, to add an AWS integration, one needs to use the UI to create the integration. This returns an external ID (and SignalFx account ID) which is then used in the trust policy of the IAM role and a subsequent call to the integration API. There doesn't exist a way to do this all within terraform. And if the current signalfx_aws_integration were to be able to do both calls to the API, there would be a circular dependency in terraform:
```
resource "aws_iam_role" "main" {
  ...
  assume_role_policy = <<EOF
// ${signalfx_aws_integration.main.external_id} and ${signalfx_aws_integration.main.signalfx_account_id} (which doesn't seem to be exported) are needed here
EOF
}

resource "signalfx_aws_integration" "main" {
  auth_method = "ExternalId"
  ...
  role_arn    = "${aws_iam_role.main.arn}"
}
```

We would like to complete the entire integration within terraform, something like:
```
resource "signalfx_aws_integration_pre" "main" {
  auth_method = "ExternalId"  
  name = "${var.account_id}"
  ...
}

resource "aws_iam_role" "main" {
  ...
  assume_role_policy = <<EOF
  // ${signalfx_aws_integration_pre.main.external_id}
  // ${signalfx_aws_integration_pre.main.account_id}
EOF
}

resource "signalfx_aws_integration" "main" {
  integration_id = "${signalfx_aws_integration_pre.main.id}"
  ...
  role_arn = "${aws_iam_role.main.arn}"
}
```

**Comment by cory-signalfx** [comment]
Thanks for making this, @kimor79! This is a great idea, and I appreciate you writing it up for me. I don't think I'll get to this today, but plan to get on it next week.

**Comment by cory-signalfx** [comment]
Alrighty, having taken a close look at this I think this is how it can work:

* A new resource `signalfx_aws_integration_pre` which is created and stores the integration's ID. It can be deleted, but has no meaningful update operation. It also has no properties, other than the computed external id.
* Add a `signalfx_aws_integration_external` which is basically the same as the current, but it *requires* an external id, which can be referenced from the `signalfx_aws_integration_pre`. This resource's create call will actually be an update. It will update normally, but have no delete. It will require the id and external_id from `signalfx_aws_integration_pre`.
* Add a `signalfx_aws_integration_token` which handles the other auth mechanism.
* Deprecate `signalfx_aws_integration`.

Does that sound sane?

**Comment by cory-signalfx** [comment]
Friends at Hashi suggested using this resource as an example: https://www.terraform.io/docs/providers/aws/r/acm_certificate_validation.html

**Comment by kimor79** [comment]
I understand why, but too bad `signalfx_aws_integration` can't be repurposed for the `_pre` resource

**Comment by cory-signalfx** [comment]
It could be! I just think it would be more ergonomic for future users that there is a difference between the external id and token based versions.

**Comment by kimor79** [comment]
yeah, I like the separation between external id and token based version. Just from a naming perspective, `signalfx_aws_integration` as the actual resource would be nice:

```
resource "signalfx_aws_integration" "foo" {
  type = "ExternalId"
}

resource "signalfx_aws_integration_external" "foo" {
  id = "${signalfx_aws_integration.foo.id}"
}

resource "signalfx_aws_integration" "bar" {
  type = "token"
}

resource "signalfx_aws_integration_token" "bar" {
  id = "${signalfx_aws_integration.bar.id}"
}
```

**Comment by cory-signalfx** [comment]
My current plan (only documenting the external for now) is:

```
resource "signalfx_aws_external_integration" "foo" {
  // Look ma, no args!
}

resource "signalfx_aws_integration" "bar" {
  external_id = ${signalfx_aws_external_integration.foo.external_id}
  integration_id = ${signalfx_aws_external_integration.foo.id}
  // all the other fields from ethis
}
```

With the `token` and `external_id` fields being set to `ConflictsWith`. This allows the majority of options to be documented in the familiarly named `signalfx_aws_integration`.

**Comment by cory-signalfx** [comment]
And for my own reference, this source is helpful: https://github.com/terraform-providers/terraform-provider-aws/blob/3270b94571f3351e44a0f7122ae3dbf1519a63a7/aws/resource_aws_acm_certificate_validation.go

**Comment by cory-signalfx** [comment]
Merged!
