### ISSUE TITLE
Terraform state is always updating

### ISSUE THREAD

**Issue by noliva** [splunk-terraform/terraform-provider-signalfx#78]
Basically, every time we run Terraform, it tries to update the same dashboards even though they already exist and is aligned because it's trying to modify a field called `time_range = 3600 -> null`

I suppose it's similar to the previous issue I opened.

**Comment by cory-signalfx** [comment]
Drat! Thanks for flagging. I'll investigate and let ya know what I find!

**Comment by cory-signalfx** [comment]
Hey @noliva!

To be clear this is the `signalfx_dashboard` resource, right? Your example uses the second-based, integer form used for charts whereas dashboards use a string-based, "-30m" style.

I'll do some digging on my end, but I can't reproduce. Can you make sure you're using the latest provider? A new one went out today!

**Comment by noliva** [comment]
happens creating a detector:

```resource "signalfx_detector" "unhealthy_hosts" {
        description       = "Calculate the percentage of unhealthy hosts"
        disable_sampling  = false
        end_time          = 0
        id                = "asdf"
        max_delay         = 0
        name              = "% of Unhealthy hosts"
        program_text      = ""
        show_data_markers = false
        show_event_lines  = false
        start_time        = 0
        teams             = [
            "asdf",
        ]
      - time_range        = 900 -> null
        url               = "https://app.signalfx.com/#/detector/asdf"

        rule {
            Unhealthy hosts > 10%"
            detect_label  = "minor"
            disabled      = false
            severity      = "Minor"
        }
        rule {
            description   = "Unhealthy hosts > 30%"
            detect_label  = "major"
            disabled      = false
            severity      = "Major"
        }
    }```

**Comment by cory-signalfx** [comment]
Excellent, thanks! I'll get on this today.
