### ISSUE TITLE
`column` on dashboard resources doesn't allow mulitple columns

### ISSUE THREAD

**Issue by nickchappell** [splunk-terraform/terraform-provider-signalfx#80]
I've been porting over my SFX dashboard TF code fro the Yelp provider to this official version, but am getting the following error:

```bash
Error: too many items for attribute "column"; cannot have more than 1
```

The code that causes this looks like roughly like this and worked with the Yelp version of the provider (resources names are anonymized and the `chart_ids` are converted to TF v0.12-compatible syntax) :

```bash
  column {
    chart_ids = "${signalfx_time_chart.1day_slo.*.id}"
    column    = 0
    width     = 4
    height    = 2
  }

  column {
    chart_ids = "${signalfx_time_chart.1week_slo.*.id}"
    column    = 4
    width     = 4
    height    = 2
  }

  column {
    chart_ids = "${signalfx_time_chart.1month_slo.*.id}"
    column    = 8
    width     = 4
    height    = 2

  }
```

The dashboard resource code has `MaxItems` set to 1: https://github.com/terraform-providers/terraform-provider-signalfx/blob/master/signalfx/resource_signalfx_dashboard.go#L131

The old Yelp version of the provider, however, doesn't have a `MaxItems` set, and allows mulitple columns: https://github.com/Yelp/terraform-provider-signalform/blob/master/src/terraform-provider-signalform/signalform/dashboard.go#L162

I'm assuming the same issue would happen with multiple `grid`s, though I don't have any dashboards laid out like that.

**Comment by cory-signalfx** [comment]
Interesting, this is not a use case I had imagined. Will get to this soon to evaluate.

The underlying difficulty is that the API has no concept of this sort of layout. The old Yelp provider did not look at the response from the API, so it didn't have to reconcile the Terraform layout with the API representation. That's a bad thing, so we fixed it. This was a casualty. More soon!

**Comment by nickchappell** [comment]
@cory-signalfx FWIW, the code with the old Yelp provider did apply and lay out the dashboard with multiple columns correctly, with no shifts from run to run in the desired vs actual state. (ie. `terraform plan` output was not changing after every single `apply`)

**Comment by cory-signalfx** [comment]
Correct! But it also never even looked at the API response! That's a whole different kind of problematic.

**Comment by cory-signalfx** [comment]
I've been thinking about this while working down some other bugs and I think I know how to do it now. I will experiment some tomorrow.

**Comment by nickchappell** [comment]
@cory-signalfx Any updates?

**Comment by cory-signalfx** [comment]
Nope, none yet. I do think this can be done, so I'll dump the ideas here for others. This is currently fairly low priority for me, but I may delegate to a teammate who's spinning up.

Because we can inspect the original schema/state of the dashboard we can iterate through each chart and check if it's entered into the column or if it stood alone. In effect, we'd use the original state as the source of truth. We already do this by checking `column` or `grid`, but we don't accommodate a world where more than one of these is used.
