### ISSUE TITLE
Issue following errors when refreshing state

### ISSUE THREAD

**Issue by noliva** [splunk-terraform/terraform-provider-signalfx#86]
Hi Cory! 

I have an issue when refreshing state:

`Error: json: cannot unmarshal number 1568826660000 into Go struct field Time.end of type int32`

The problem is I can't find where the error happens easily, is there a way to find out why suddenly my state is corrupted?

If there was a way to find to which detector/dashboard it points, I could delete and recreate it, but now I need to do this manually one by one.

**Comment by cory-signalfx** [comment]
Eep!

That's alarming. I'll have to double check the various spots this is defined. Maybe the original OpenAPI spec I used has an error on this data type and uses an int32 when it should be an int64.

You can use `terraform show` to dump the state of your directory. There is also a `-json` flag so you can use it with something like `jq` and grab every `end`. Gimme a sec and I'll whip up something for ya.

**Comment by cory-signalfx** [comment]
This might help you track it down:

```terraform show -json | jq '.values.root_module.resources[] | "\(.address) \(.values.end_time)"'```

**Comment by noliva** [comment]
Ok, thanks, as we only faced this in a staging environment, I deleted the .tfstate manually (and the resources) and recreated it, not sure how it got into that state as when recreating it, it worked fine.

Still, thank you very much for your quick response and for adding it here, if it happens again I know how to track it now 😄

**Comment by cory-signalfx** [comment]
No problem. This is likely a bug and I will still get a fix in for it. I think this needs to be an int64 for sure. Just trying to prove it!

**Comment by cory-signalfx** [comment]
Fix applied!
