### ISSUE TITLE
Member/User Support

### ISSUE THREAD

**Issue by cory-signalfx** [splunk-terraform/terraform-provider-signalfx#9]
For #3, it would also be nice to have member/user support. This is not possible at present because SignalFx's API lacks a user-update API call. Leaving this here until we have a fix.

**Comment by nickchappell** [comment]
As an interim step, could the `signalfx_team` resource be modified so it can have a list of (already created) user IDs added? Right now, I can't manage my SFX teams via TF, since TF always wants to delete any members added via the UI after the team is created via TF.

**Comment by cory-signalfx** [comment]
Ugh, @nickchappell I'm sorry. You _can_ do this today it's just completely undocumented! Lemme make a PR right now for that. In the meantime, you can use `members = [ "abc123", "abc124", … ]`.

**Comment by cory-signalfx** [comment]
In master now, will get a build out today.
